### ISSUE TITLE
[Feature request]: Use a signalr client?

### ISSUE THREAD

**Issue by bjsmiley** [acheong08/EdgeGPT#1]
Just passing by, scrolling through the code. And recognized the [signalr protocol ](https://github.com/dotnet/aspnetcore/blob/main/src/SignalR/docs/specs/HubProtocol.md#overview)
https://github.com/acheong08/EdgeGPT/blob/f17417b869cb4f4159f2c4903abf16fc65ee3e98/src/EdgeGPT.py#L176-L178

Was just curious if you thought of using a preexisting signalr client instead of implementing the protocol.

**Comment by acheong08** [comment]
Planning on migrating to https://github.com/mandrewcito/signalrcore later. Websockets is easier to implement for now.

**Comment by acheong08** [comment]
After implementing the same thing in 2 different SignalR libraries, I have decided to stick with websockets. The level of abstraction is too high and is difficult to use for reverse engineering.

**Comment by acheong08** [comment]
I used Insomnia to reverse it

**Comment by pneb** [comment]
> I used Insomnia to reverse it

Oh, cool then.
