### ISSUE TITLE
AttributeError when running example code

### ISSUE THREAD

**Issue by ComradeCat1** [acheong08/EdgeGPT#105]
When I try running the example code from README.MD, I get the following error:
'str' object has no attribute 'value'
  File "C:\Users\tudor\Documents\pi_epsilon\enpcilon_api\text_generator.py", line 6, in main
    print(await bot.ask(prompt="Hello world", conversation_style="creative"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tudor\Documents\pi_epsilon\enpcilon_api\text_generator.py", line 11, in <module>
    asyncio.run(main())
AttributeError: 'str' object has no attribute 'value'
The code I tried to run is:
import asyncio
from EdgeGPT import Chatbot

async def main():
    bot = Chatbot(cookiePath='./cookies.json')
    print(await bot.ask(prompt="Hello world", conversation_style="creative"))
    await bot.close()

if __name__ == "__main__":
    asyncio.run(main())
    
By the way the content of the cookies.json file is the cookies I got from the cookie editor chrome extension. (I clicked Export just like the README.MD file said)
Why is this error happening?

**Comment by XiaoXinYo** [comment]
[comment](https://github.com/acheong08/EdgeGPT/pull/101#issuecomment-1454770971) 

You can use it as a reference，I wonder if it is right。

**Comment by ComradeCat1** [comment]
I clicked the link you gave me, and the code from that link worked. I added the line "from EdgeGPT import ConversationStyle" I replaced conversation_style="creative" with conversation_style=ConversationStyle.creative
But now it gave me a HUGE Dictionary. I think I can extract the information I need from that dictionary.
I don't need help anymore (for now), so I'll close this issue.
