### ISSUE TITLE
Python 3.7 broken

### ISSUE THREAD

**Issue by SashaXser** [acheong08/EdgeGPT#109]
Who do you have to be to write like that?
I wait response like: "Update python lol"

Mar 5 11:40:05 AM  Traceback (most recent call last):
Mar 5 11:40:05 AM    File "main.py", line 7, in <module>
Mar 5 11:40:05 AM      from EdgeGPT import Chatbot, ConversationStyle
Mar 5 11:40:05 AM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/EdgeGPT.py", line 130, in <module>
Mar 5 11:40:05 AM      class Conversation:
Mar 5 11:40:05 AM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/EdgeGPT.py", line 135, in Conversation
Mar 5 11:40:05 AM      def __init__(self, cookiePath: str = "", cookies: dict | None = None) -> None:
Mar 5 11:40:05 AM  TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Mar 5 11:35:30 AM    File "main.py", line 8, in <module>
Mar 5 11:35:30 AM      from EdgeGPT import Chatbot, ConversationStyle
Mar 5 11:35:30 AM    File "/opt/render/project/src/.venv/lib/python3.7/site-packages/EdgeGPT.py", line 14, in <module>
Mar 5 11:35:30 AM      from typing import Literal
Mar 5 11:35:30 AM  ImportError: cannot import name 'Literal' from 'typing' (/usr/local/lib/python3.7/typing.py)

**Comment by acheong08** [comment]
> I wait response like: "Update python lol"

Yes.
