### ISSUE TITLE
TooManyRedirects: Exceeded 30 redirects.

### ISSUE THREAD

**Issue by DrgZong** [acheong08/EdgeGPT#113]
**提交 issue 前，请先确认：**
- [x] 我已看过 **FAQ**，此问题不在列表中
- [x] 我已看过其他 issue，他们不能解决我的问题 
- [ ] 我认为这不是 Mirai 或者 OpenAI 的 BUG

**表现**  
使用cookiePath运行到此处时会报错
![image](https://user-images.githubusercontent.com/19589495/223094183-6e34ff98-45bd-4476-a7e0-dab64cb3305b.png)

**运行环境:**  
- 操作系统：MacOS（Apple M1 Pro）
- Docker： 无
- 项目版本：0.0.55

**复现步骤**  
描述你是如何触发这个 BUG 的
1. 启动时报错

**预期行为**  
正常启动

**截图**  
![image](https://user-images.githubusercontent.com/19589495/223094514-47d9eb13-fb1d-439c-8109-a3a164ea6043.png)

**Comment by Harry-Jing** [comment]
May use httpx to repalce requests？

httpx support better handling redirection

**Comment by Cvandia** [comment]
I've tried to change it to```httpx.Client```, it's all like an error ```Too many redirects```
(尝试改成httpx.Client，都是类似报错```太多重定向```.)

**Comment by Cvandia** [comment]
I've fixed the issue by fetching ```cookies``` in the ```AI dialog``` interface instead of ```www.bing.com```（我已经解决该问题，在ai对话界面获取cookie，而不是在bing.com)

**Comment by Cvandia** [comment]
I tried a solution myself: clear the ```browser's cookies``` about visiting ```bing.com```, get new cookies, and avoid excessive redirects(我自己尝试了一种方案：清除浏览器关于访问bing.com的cookie，获得到新的cookie，避免过多的重定向）

**Comment by cx9208** [comment]
meet same problem

**Comment by wangmw3617** [comment]
same probiem

**Comment by Harry-Jing** [comment]
I use httpx to solve this problem
https://github.com/Harry-Jing/nonebot-plugin-bing-chat/blob/main/nonebot_plugin_bing_chat/common/bing.py
and headers is different form websocket connection
