### ISSUE TITLE
 Can someone introduce what’s the purpose of this project? I do not understand it.

### ISSUE THREAD

**Issue by alanjustalan** [acheong08/EdgeGPT#117]
It seems that there is no specific function introduction, which makes me a little confused. Can someone introduce it?

**Comment by EsqerYasen** [comment]
i am using for automation. like i have so many question  only one parameter are different . this project is very usefull.

**Comment by scmanjarrez** [comment]
I use it on my telegram bot, instead of using Microsoft Edge I just use the bot to interact with BingChat (EdgeGPT)

**Comment by PRO-2684** [comment]
It allows you to easily integrate bing ai into various projects. For example, you may use it in your Telegram bot, or you might want to write a better frontend/application for bing ai.
