### ISSUE TITLE
If no message is sent, the connection will be interrupted after a while. Is there a way to support reconnection and continue the previous conversation, like the side panel on a webpage?

### ISSUE THREAD

**Issue by DreamMaoMao** [acheong08/EdgeGPT#136]
![image](https://user-images.githubusercontent.com/30348075/225487964-8cab9189-1279-410c-ad68-f809725d3702.png)

**Comment by 296095958** [comment]
i have the same problem

**Comment by acheong08** [comment]
I now ensure it's open by reconnecting every time like the website does
