### ISSUE TITLE
Why do answers take sooo long?

### ISSUE THREAD

**Issue by CyberTimon** [acheong08/EdgeGPT#14]
Is this the normal speed of edge/binggpt? or am I doing something wrong?
I have to wait like 1-2min for a simple respond like: Hello I'm bing search, how can I help you?

**Comment by acheong08** [comment]
Trying using `--stream` to see when the initial response starts

**Comment by acheong08** [comment]
It takes ~2 seconds for me

**Comment by Jimmy-Z** [comment]
I suggest stream by default, use `--no-stream` for previous behavior.

**Comment by acheong08** [comment]
> I suggest stream by default, use `--no-stream` for previous behavior.

Agreed. Mind adding that to your PR?

**Comment by acheong08** [comment]
Edit: I'll do it

**Comment by acheong08** [comment]
Done
