### ISSUE TITLE
KeyError: 'messages'

### ISSUE THREAD

**Issue by miningblob** [acheong08/EdgeGPT#144]
I'm getting a "KeyError" when trying to use this. Here is the line of code where the error is:
`response = await bot.ask(prompt=prompt`
The weird thing is, the code worked perfectly fine last week without any changes. Has the bing API changed? If so, is there an updated EdgeGPT? Or am I doing it wrong?
Here is the full error:
`Exception has occurred: KeyError
'messages'
  File "\text bot.py", line 8, in main
    response = await bot.ask(prompt=input("User: "))
  File "\text bot.py", line 25, in <module>
    asyncio.run(main())
KeyError: 'messages'`
Hope this gets fixed soon

**Comment by acheong08** [comment]
Should be
