### ISSUE TITLE
Request is throttled

### ISSUE THREAD

**Issue by AS7RIDENIED** [acheong08/EdgeGPT#145]
resp={'type': 2, 'invocationId': '0', 'item': {'firstNewMessageIndex': None, 'conversationId': '51D|BingProd|37F3A13C7C2608764363A55DA0448A3B790AAADB9C912B8A75344F2770C16679', 'requestId': 'eaf13e9a-fc12-4916-9773-38e826821ff9', 'telemetry': {'metrics': None, 'startTime': '2023-03-16T21:58:02.8928935Z'}, 'result': {'value': 'Throttled', 'message': 'Request is throttled.', 'error': 'Request is throttled.', 'serviceVersion': '20230316.51'}}}
How can i fix that?

**Comment by acheong08** [comment]
It's from Bing. I can't fix
