### ISSUE TITLE
The issue is that the results are inconsistent with the official interface

### ISSUE THREAD

**Issue by liuyubiao** [acheong08/EdgeGPT#148]
Dear author, hello. Thank you for open-sourcing this project. The results obtained from using the current project are inconsistent with those on the official website in some cases. It seems that only the retrieval results have been obtained, and when there is no retrieval result, the information indicating no retrieval result is returned. However, on the official website, results are generated as shown in the figure below. May I ask where I can improve to get the same results as on the official website?
Bing Chat
![websit](https://user-images.githubusercontent.com/13082828/225830587-ffc8852b-2c23-433b-8b30-cb0cf20aaebc.jpg)
Current Response
{
	'type': 2,
	'invocationId': '0',
	'item': {
		'messages': [{
			'text': '帮我查找旺仔牛奶的配料表',
			'author': 'user',
			'from': {
				'id': '985157535441414',
				'name': None
			},
			'createdAt': '2023-03-17T06:37:46.7674164+00:00',
			'timestamp': '2023-03-17T06:37:46.7650048+00:00',
			'locale': 'en-us',
			'market': 'en-us',
			'region': 'us',
			'messageId': '3e829d49-5111-45cb-9ba8-d643738aa6ab',
			'requestId': '3e829d49-5111-45cb-9ba8-d643738aa6ab',
			'offense': 'None',
			'feedback': {
				'tag': None,
				'updatedOn': None,
				'type': 'None'
			},
			'contentOrigin': 'cib',
			'privacy': None,
			'inputMethod': 'Keyboard'
		}, {
			'text': '你好，这是必应。我可以帮你查找旺仔牛奶的配料表。根据网上的信息[^1^]，旺仔牛奶是一种调味乳，它添加了额外的牛奶香精和糖，含糖量约为10%。它的生产工艺包括原料乳的验收、过滤、净化、标准化、均质、杀菌、冷却和灌装[^2^]。旺仔牛奶的口感被认为是非常过瘾和适合儿童青少年[^1^]。',
			'author': 'bot',
			'createdAt': '2023-03-17T06:38:05.3770783+00:00',
			'timestamp': '2023-03-17T06:38:05.3770783+00:00',
			'messageId': '52343b2d-a64a-47ab-aaa3-bbcc35e2aaec',
			'requestId': '3e829d49-5111-45cb-9ba8-d643738aa6ab',
			'offense': 'None',
			'adaptiveCards': [{
				'type': 'AdaptiveCard',
				'version': '1.0',
				'body': [{
					'type': 'TextBlock',
					'text': '[1]: https://www.zhihu.com/question/20970974 "为什么旺仔牛奶卖得贵还这么流行？ - 知乎"\n[2]: https://baike.baidu.com/item/%E6%97%BA%E4%BB%94%E7%89%9B%E5%A5%B6/3182289 "旺仔牛奶_百度百科"\n[3]: https://www.amazon.com/Wangzai-Milk-Drink-%E6%97%BA%E4%BB%94%E7%89%9B%E5%A5%B6-Bottles/dp/B07VN7JQ37 "Wangzai Milk Mix Drink 旺仔牛奶 (6 Bottles Pack) Wang Wang Milk Drink Want ..."\n\n你好，这是必应。我可以帮你查找旺仔牛奶的配料表。根据网上的信息[^1^][1]，旺仔牛奶是一种调味乳，它添加了额外的牛奶香精和糖，含糖量约为10%。它的生产工艺包括原料乳的验收、过滤、净化、标准化、均质、杀菌、冷却和灌装[^2^][2]。旺仔牛奶的口感被认为是非常过瘾和适合儿童青少年[^1^][1]。\n',
					'wrap': True
				}, {
					'type': 'TextBlock',
					'size': 'small',
					'text': 'Learn more: [1. www.zhihu.com](https://www.zhihu.com/question/20970974) [2. baike.baidu.com](https://baike.baidu.com/item/%E6%97%BA%E4%BB%94%E7%89%9B%E5%A5%B6/3182289) [3. www.amazon.com](https://www.amazon.com/Wangzai-Milk-Drink-%E6%97%BA%E4%BB%94%E7%89%9B%E5%A5%B6-Bottles/dp/B07VN7JQ37)',
					'wrap': True
				}]
			}],
			'sourceAttributions': [{
				'providerDisplayName': '为什么旺仔牛奶卖得贵还这么流行？ - 知乎',
				'seeMoreUrl': 'https://www.zhihu.com/question/20970974',
				'imageLink': 'https://bing.com/th?id=OIP.11OtY3CDQNID_q-jh6EEFAAAAA&pid=cdx',
				'imageWidth': '450',
				'imageHeight': '600',
				'imageFavicon': 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAZXSURBVFhHjZfbblw1FIbtN0jfYOcN4A3mEfoG3ZVoWkppp/SQnkKm5zNMz5S2JDQ0hbY0UJAQCDQIBAhxyBUIEFAQSNxAcgXc7c33L3vt2RkQiqV/bC9727/XyZ6wovSqdeFQNQhHqmVQheN1HU9Qn6rrcAacpf8s/T71eXAR2SVwBTxH/ypj16ivU7+AbAa8SH+O+iVwi7Xn2eNfZboeC1PVIE7z4UEmHuajw7SPUovESWQicZr2GeTP0BaJc7QvABG5DCARrgJIhOvgBnMgEUXiJn0RuQVuV4uQG8u7hxD3IjjApKerKvaYAIl4SKB/jP5R6uPgJDjFhmginKWWNs7RPk8tTVymljZE4nkAiXgDmWsCEnGOvkjMow0rk3UZ9yLYx6CRoC0SQCSkDZnDiJwAaCKiCSORNWEkLgBIxEttEnx3DaAJIzHLeFsTMkfcDZNJOpCI+/h4P+0pMA2cxBGAOUwTx5iDSUwT+EU0TVD3qSERL1K3/EKaiC1zOInkF9LCTjq76IjEHtpook2i+1ZdL/9d14XU7ETwi4BJkk/QljZEAk3IOc0npA1MEq8wTyTknNKEOScyTBLmcPbwFAOQCCKxm/YeBvfyISTKV2sri78xJueUX8gxZY6siYBfeISIxNA5qWWOxjlpO4mWX4SwHeF2BDvoZBKmCUgsfJ0I9D+p6w6sO3xguEmbsOpgR0XIGk7eeQXcAXfBPQD5zn2wAF4DD1jX/cJMkkmErfx0AUTCDoSZRIHDraaUbyaspgTMEdsRInPELQi3snFDAuysqpITqcj+gx/r+uFyq/9wiPKNul4PmrGfwS8r4aUJ1eycli/CZgg8CRs0EZ0EfjH4Pn3U/xA5ftF7N/VnFhknVIf5ArKoV0WbN0lLfkGYFtjci2dOOWdDIjzOz2awBUAkbMNeTFR5uMQCyoRESEPgS+aQL0TC8gUkytfT2OAn5ipXZBKKkIJTerH07fnCSYSNdCARpQnMIRJr+ah7v6rWkBc8QnrvpEVmvqBPhMQDzM0k1uNkKiJgYaoIgYgyZ8EpvVjSUpiKhKVv5oUJGpnEqCbMLzCH/KL3dlpk5nP6SlrKFVkTJZ6uYgRauUJJq+CUXixMSd8pX7C5SEQRyCTMHMITTBCJlnM2BD6jj0lS+mZc+YJwUzEC+Q6xi4zMOc4p0yhjp5ErfYuIk9DmIhEn6IjIJuzGyQbf4QO/gz8Slv9Ki8jT5RsGIkM+4QlLUeHOaXcIN2qBvb3YHYJfRCeh9D1KQHX/vfzFKoqIlPfSKY2AIqR1rRfZoVUUITE7Z0PCNx8SqOsx1D6Oeov9gDuhYNHFX9Mia3WpjGTO9XcyAfKF3SFyTu4RESlwOi/mF4oQe+Sw5xnqRvUZjU8YmLSJcZzTTfAoHzf5AhKxlbREQM4ZRWKK7yAxjprTKHL5hUjoIpMmdI+MEhCMxIYsxzk7XLlaQCQKFu2/jxwSronyZVs/aSA7p78tCtTsxfzCSXi+aDZmQzOHokG1EwCzH6cF3DFVuni+R0h5O8kGP9Cf5DuFKZeZwnQcNadRxvS2yCSCP3AaAiNw3xgnDefv65KbsHu3rQ022YYJ5m3Y0rf8gkdOpRtVr6wCz/diD5weBz3IuOcLV3XaEMEGbyf57EfpY528kHrR0ODbJJNGlC9KruV26fAaWvgqd1rF75AUJRARiXTitNkoSu5rL9MP+CCTHedky38muSKk5G2wmhJI382bM5MwDdjJR/AI9vJNdHrJTCuZRDd7/pjC0dM3N6pHS/8DHipEQ9zFfJmj7ZxEiCUsYbgwHW3OBiUPR9988I1UnzZNc9Mc1TKPMmfUHaL0zWU2+2m6TYdvC+R6Zdmbk3Xym1Mk7OGLWpcaDeSFO7zvpP6O7nSX5zHvD+fThkRzh9iNCrjMPEyjvbSAiJgmkJHkLF9g/4E7ni06Cm3mG4LReepb6PplBgmZxB44REjoslG+URsSZhLa+/Qs38Cfg2ax/9gon7xtf3NGkwOXaa6T8Gtd7818rZs2Vry+qffk/4ksMvCFVmz+P2gSVou0QfKcvk0TMok/fBtNgEn+DjZlHX8UJxC0SKxoZ/iJjaCZLbeb8VwbCdAyyfD1zbo7Uf221p/TpjxWl8knhpuvShuZiBNzWdiIfBghSzxwBvhE6+95CP8A6v7GFtNHJ/MAAAAASUVORK5CYII=',
				'searchQuery': '旺仔牛奶'
			}, {
				'providerDisplayName': '旺仔牛奶_百度百科',
				'seeMoreUrl': 'https://baike.baidu.com/item/旺仔牛奶/3182289',
				'searchQuery': '旺仔牛奶'
			}, {
				'providerDisplayName': 'Wangzai Milk Mix Drink 旺仔牛奶 (6 Bottles Pack) Wang Wang Milk Drink Want ...',
				'seeMoreUrl': 'https://www.amazon.com/Wangzai-Milk-Drink-%E6%97%BA%E4%BB%94%E7%89%9B%E5%A5%B6-Bottles/dp/B07VN7JQ37',
				'imageLink': 'https://bing.com/th?id=OIP.n6Pnu8ePLbhlmHjAZKwRsQHaHa&pid=cdx',
				'imageWidth': '500',
				'imageHeight': '500',
				'imageFavicon': 'iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAMASURBVFhHtVe/axRBFD64S0BIFRsLYyt2ufTaaMDSFOYPELyUQiCHlZ2pFVMKgQPRJnrRJoJnitgY7wiEBDwttLkD0xhu1SLKje/bmbf3dnZuZ4x3H3zs7ezb9773Y3ZvCwyl1BTxbr/f/0jHsYB87xOXiWdMWA1auEj8bOzGDgihw4U4OP2Y+tfgvV5PNZvNhK1WS3W7XXM1DEbEJLK/p5f8eFGvq2vz86o0MZGwKH7jGmxCQbHvQIA3e2QM5zJYHqvVqrnTiyZa4MXNxcVUgGKp5BUTUglK/pdXQJ0cuQLMzs3FwuyWMK/Segi8Am5XKhnndolxbtuAIfAKqCwtZRxjJiTa7XbcEibbhSBoBuS2w5ZzQQoEISQEQQJsYM9DzKO1tZg8pBjOsQlA0Purq/HwcRAZzLUWgiAB2FLnZ2YyQTiQax0MgVcASg1nHEgGxPSjBY1GI1ljjqwCs+Vyxjn2fqfTMRYatg0YglwB2F4ux6iKBOaDr8lKhSBXQH1zM+V0mGNXC8CQN2SuAPTX5dh+ELkeViAS8CFXAGcm9zcoH8W1Wi1jwxUr05a1xdrIFSB7K4kAGE5sTdke2wZHVDEPuQIA+1U8jK4HFARikPPgFcB/RmznXHJkipZEUZS8FblCvuCAVwAAESglC0FwZIzhs7ckHtdYjyLR+x/0zDj6oNS3XaVO0jORFnDwQKkvG+ZkBPhJgd/eUOoZhXlqeEgxBNICvtMnwcZZfRMU/y9+R9oPKoDMX13SSQqkBQAw3Lqi1UIIKnJCjk6DzptBBZAcfKINAvhX/Mf8HgAi3i8npevjxne3tHpkZPUxBtZw7dO6tkUlcR98fH2uxbymxNI4hgB8ILgBhy+pbOxI9pIp19iGuU3ZH5svvSPKHFUQoNg7ELBizocDGWxdHgSTR2JcISlil6oXNkMVslaTJGJPn3uAqYaYw4e6t+D2wqA9KLOrPQ4gezoU+fvwHC343xwjAsV6QpyOg0vQ4gJxnTh8Lk4J8rlHfEy8bsIRCoW/g/PKPUlnry4AAAAASUVORK5CYII=',
				'searchQuery': '旺仔牛奶'
			}],
			'feedback': {
				'tag': None,
				'updatedOn': None,
				'type': 'None'
			},
			'contentOrigin': 'DeepLeo',
			'privacy': None,
			'suggestedResponses': [{
				'text': '旺仔牛奶有什么好处？',
				'author': 'user',
				'createdAt': '2023-03-17T06:38:32.5329881+00:00',
				'timestamp': '2023-03-17T06:38:32.5329881+00:00',
				'messageId': 'eefc0e3a-c606-41ef-aabe-b51e2d7d449a',
				'messageType': 'Suggestion',
				'offense': 'Unknown',
				'feedback': {
					'tag': None,
					'updatedOn': None,
					'type': 'None'
				},
				'contentOrigin': 'DeepLeo',
				'privacy': None
			}, {
				'text': '旺仔牛奶有哪些口味？',
				'author': 'user',
				'createdAt': '2023-03-17T06:38:32.5329907+00:00',
				'timestamp': '2023-03-17T06:38:32.5329907+00:00',
				'messageId': 'fd8ba6c0-93cc-4c09-9dd9-a4cdf35293b2',
				'messageType': 'Suggestion',
				'offense': 'Unknown',
				'feedback': {
					'tag': None,
					'updatedOn': None,
					'type': 'None'
				},
				'contentOrigin': 'DeepLeo',
				'privacy': None
			}, {
				'text': '旺仔牛奶在哪里可以买到？',
				'author': 'user',
				'createdAt': '2023-03-17T06:38:32.5329911+00:00',
				'timestamp': '2023-03-17T06:38:32.5329911+00:00',
				'messageId': '1c376908-8d55-4b5f-b18e-ef4107a8be74',
				'messageType': 'Suggestion',
				'offense': 'Unknown',
				'feedback': {
					'tag': None,
					'updatedOn': None,
					'type': 'None'
				},
				'contentOrigin': 'DeepLeo',
				'privacy': None
			}],
			'spokenText': '旺仔牛奶的口感被认为是非常过瘾和适合儿童青少年'
		}],
		'firstNewMessageIndex': 1,
		'conversationId': '51D|BingProd|DC7DF5297F723E16183672581E746CC88AF63242FDE6D8534F9D168F4C60725B',
		'requestId': '3e829d49-5111-45cb-9ba8-d643738aa6ab',
		'conversationExpiryTime': '2023-03-17T12:38:32.6145746Z',
		'shouldInitiateConversation': True,
		'telemetry': {
			'metrics': None,
			'startTime': '2023-03-17T06:37:46.7650647Z'
		},
		'throttling': {
			'maxNumUserMessagesInConversation': 15,
			'numUserMessagesInConversation': 1
		},
		'result': {
			'value': 'Success',
			'message': '旺仔牛奶',
			'serviceVersion': '20230316.51'
		}
	}
}

**Comment by WWRichard** [comment]
```python
 parser.add_argument(
        "--style",
        choices=["creative", "balanced", "precise"],
        default="balanced",
    )
``` 
默认balanced
确认类型

**Comment by liuyubiao** [comment]
> 帮我查找旺仔牛奶的配料表

感谢回复，这个结果是都将style设置成creative得到的，与bing网站呈现的结果不一致，请问您那边是正常的吗？

**Comment by liuyubiao** [comment]
> ```python
>  parser.add_argument(
>         "--style",
>         choices=["creative", "balanced", "precise"],
>         default="balanced",
>     )
> ```
> 
> 默认balanced 确认类型

感谢回复，这个结果是都将style设置成creative得到的，与bing网站呈现的结果不一致，请问您那边是正常的吗？

**Comment by acheong08** [comment]
Something broke today. Fixing it

**Comment by liuyubiao** [comment]
> 由于其他参数，可能存在细微差异。我还在想那些



> There might be slight differences due to other parameters. I am still figuring those out

Thank you for your work. I look forward to your reply.

**Comment by acheong08** [comment]
Seems to be region based. I don't include location data in the request

**Comment by liuyubiao** [comment]
> 我不在请求中包含位置数据

Understood. Thank you very much.
