### ISSUE TITLE
if self.session and not self.session

### ISSUE THREAD

**Issue by Do1e** [acheong08/EdgeGPT#149]
https://github.com/acheong08/EdgeGPT/blob/e0d9927465efe08f4fda8f18982eda6d8c184a87/src/EdgeGPT.py#L296

这一行有问题，应该是`if self.session and not self.session.close`才对  
There's something wrong with this line. It should be this `if self.session and not self.session.close`

**Comment by acheong08** [comment]
fixed

**Comment by acheong08** [comment]
There is something wrong with aiohttp. Proxy must be set from environment variables for now `all_proxy=socks5://host:port`

**Comment by callzhang** [comment]
shoud be `if self.session and not self.session.closed`

**Comment by acheong08** [comment]
Just removed the session thing altogether. aiohttp was causing a lot of other issues. I'll perhaps introduce it back again but slowly
