### ISSUE TITLE
What is the reason for the TimeoutError error

### ISSUE THREAD

**Issue by DreamMaoMao** [acheong08/EdgeGPT#155]
![image](https://user-images.githubusercontent.com/30348075/225897575-1695b250-e510-4196-b7c4-2da02d647b52.png)

**Comment by VMTask** [comment]
I find the problem!
![Picture](https://i.328888.xyz/2023/03/18/MZmhJ.png)
We can't use IPV6 in china to connect Microsoft's server!
Turn Off the IPV6 can fix this error.
