### ISSUE TITLE
docs: Inform users they do not have to use Edge to check access

### ISSUE THREAD

**Issue by Christopher-Hayes** [acheong08/EdgeGPT#157]
I'm creating this issue ahead of making a pull request for an update to the README. If in agreement, I can go ahead and make that PR.

To check Edge access, users actually don't have to get/open Edge. Microsoft is blocking non-Edge users from using Bing Chat by checking their user-agent.

The README can be updated to tell users that they can also check access on any browser if they set their `user-agent` to look like they're using Edge (ie `Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edg/109.0.1474.0`). This can be easily done with an extension like ["User-Agent Switcher and Manager"](https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg)

**Comment by acheong08** [comment]
+1
