### ISSUE TITLE
Can change the default chat address

### ISSUE THREAD

**Issue by VMTask** [acheong08/EdgeGPT#158]
If you use IPV6 in China, you will encounter a TimeoutError.
Like this:
![MiOSz.png](https://i.328888.xyz/2023/03/18/MiOSz.png)
I want to be able to set the primary address of the request myself and use the environment variable `MAIN_URL` to set it

**Comment by acheong08** [comment]
Feel free to make a pull request

**Comment by VMTask** [comment]
#209
