### ISSUE TITLE
ImageGen 返回错误页面

### ISSUE THREAD

**Issue by youminxue** [acheong08/EdgeGPT#169]
![image](https://user-images.githubusercontent.com/3829455/226858276-5e8e04a7-59e3-4910-a1cb-0445e120d99a.png)
命令是：
python3 -m ImageGen --cookie-file ./cookies.json --prompt "Based on the previous plot, the Little Bull Demon had a distinct and vivid appearance. With a sturdy and well-built body, it stood upright like a human, yet retained its bovine features. Its head was adorned with a pair of curved horns, while its face displayed a mixture of human and ox traits. Sharp eyes, a flat nose, and a wide mouth with slightly protruding teeth completed the look. The Little Bull Demon's skin was covered in coarse, dark fur, giving it a rugged appearance" --output-dir .

**Comment by acheong08** [comment]
> python3 -m ImageGen --cookie-file ./cookies.json --prompt "Based on the previous plot, the Little Bull Demon had a distinct and vivid appearance. With a sturdy and well-built body, it stood upright like a human, yet retained its bovine features. Its head was adorned with a pair of curved horns, while its face displayed a mixture of human and ox traits. Sharp eyes, a flat nose, and a wide mouth with slightly protruding teeth completed the look. The Little Bull Demon's skin was covered in coarse, dark fur, giving it a rugged appearance" --output-dir .

Looks too long. Use a shorter prompt

**Comment by acheong08** [comment]
> I get 'Redirect failed' :(

Go over to https://www.bing.com/images/create and see if it works there. If it does, get new cookies

**Comment by phamxtien** [comment]
> > I get 'Redirect failed' :(
> 
> Go over to https://www.bing.com/images/create and see if it works there. If it does, get new cookies

Done with new cookies

**Comment by acheong08** [comment]
Could you post some debug such as the error content?

**Comment by acheong08** [comment]
Upgrade if boosts ran out
