### ISSUE TITLE
Exception: Authentication failed with Status code: 404

### ISSUE THREAD

**Issue by cool-xuan** [acheong08/EdgeGPT#178]
Thanks a lot for your awesome work first.

Prior to this day, EdgeGPT was working well, but unexpectedly, an exception has arisen. Despite my attempts to upgrade EdgeGPT to the most newest version (0.1.3) and to refresh my cookie file, this exception persists.

Besides, a Status Code 404 is reported.

Precisely, when I try to run `python -m EdgeGPT --cookie-file ./cookies.json`, the shell outputs:

        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit
    
        Initializing...
        Enter `alt+enter` or `escape+enter` to send a message
        Status code: 404
        A looooooooooooooooooooong code (like html codes)
        Traceback (most recent call last):
          File "/home/zhouyixuan/miniconda3/envs/edgegpt/lib/python3.8/runpy.py", line 194, in _run_module_as_main
            return _run_code(code, main_globals, None,
          File "/home/zhouyixuan/miniconda3/envs/edgegpt/lib/python3.8/runpy.py", line 87, in _run_code
            exec(code, run_globals)
          File "/home/zhouyixuan/chatgpt/EdgeGPT/src/EdgeGPT.py", line 467, in <module>
            asyncio.run(main())
          File "/home/zhouyixuan/miniconda3/envs/edgegpt/lib/python3.8/asyncio/runners.py", line 44, in run
            return loop.run_until_complete(main)
          File "/home/zhouyixuan/miniconda3/envs/edgegpt/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
            return future.result()
          File "/home/zhouyixuan/chatgpt/EdgeGPT/src/EdgeGPT.py", line 378, in main
            bot = Chatbot()
          File "/home/zhouyixuan/chatgpt/EdgeGPT/src/EdgeGPT.py", line 308, in __init__
            self.chat_hub: ChatHub = ChatHub(Conversation(self.cookiePath, self.cookies))
          File "/home/zhouyixuan/chatgpt/EdgeGPT/src/EdgeGPT.py", line 220, in __init__
            raise Exception("Authentication failed")
        Exception: Authentication failed

**Comment by DreamMaoMao** [comment]
i have the same problem!   what happen?

**Comment by cool-xuan** [comment]
@DreamMaoMao I suspect that Edge is only available in specific regions and unfortunately, China is currently blocked. 😭

**Comment by yduanBioinfo** [comment]
I have the same problem too.

**Comment by Harry-Jing** [comment]
Now you can't access https://edgeservices.bing.com/edgesvc/turing/conversation/create when you use China's IP

**Comment by DreamMaoMao** [comment]
Chinese IP addresses can access this link, but it seems that the link has been moved and is no longer valid, resulting in a 404 error @Harry-Jing

**Comment by yduanBioinfo** [comment]
As you said, I can't access the link right now.  The following is the response when I try to reach that link:
<h2>Our services aren't available right now</h2><p>We're working to restore all services as soon as possible. Please check back soon.</p> 0scYbZAAAAAA5aSklsq20Q7e9xNqoeKDbQkoxRURHRTEwXXXXXXXXX==

Can I suppose that the rules for Chinese IP for this link will be consistent with what is for the link www.bing.com/NEW?
And I can't use this package until Microsoft changes its IP rules for both edgeservices.bing.com and NEWBING?
________________________________
发件人: GreamMaoMao ***@***.***>
发送时间: 2023年3月23日 11:51
收件人: acheong08/EdgeGPT ***@***.***>
抄送: yduanBioinfo ***@***.***>; Comment ***@***.***>
主题: Re: [acheong08/EdgeGPT] Exception: Authentication failed with Status code: 404 (Issue #178)


Chinese IP addresses can access this link, but it seems that the link has been moved and is no longer valid, resulting in a 404 error @Harry-Jing<https://github.com/Harry-Jing>

―

**Comment by DreamMaoMao** [comment]
![QQ截图20230323123037](https://user-images.githubusercontent.com/30348075/227103694-9b0f008c-ed2a-4775-95f4-cac77aca8ea5.png)
when i turn on vpn


![QQ截图20230323122718](https://user-images.githubusercontent.com/30348075/227103842-a11b22f0-d021-40a3-afe4-fedd41625a7b.png)
when i turn off the vpn 

so,we can infer that the interface has not changed 。just the server detects the Chinese ip and returns 404

**Comment by KamiPasi** [comment]
需要加代理

**Comment by acheong08** [comment]
`export all_proxy=socks5://127.0.0.1:1080/`

**Comment by tom68-ll** [comment]
I have the same question

**Comment by chswy123** [comment]
Yes, I have the same problem

**Comment by WhitneyYan** [comment]
如果用的是v2rayN做代理，可以看看这个[https://github.com/2dust/v2rayN/issues/2065]，然后把代理开了也不报错。
我没升级v2rayN，就用的这种方法。
![image](https://user-images.githubusercontent.com/55488961/227115682-46612b97-7c7b-4655-a83c-36e3698e9235.png)

**Comment by acheong08** [comment]
我用的是 https://github.com/p4gefau1t/trojan-go

**Comment by MetorSage** [comment]
If you are using a Chinese IP, please use a proxy. If this still happens, please check the proxy rules. Some proxy rules set Microsoft services to be directly connected. Modify them to use a proxy instead.

**Comment by cool-xuan** [comment]
> If you are using a Chinese IP, please use a proxy. If this still happens, please check the proxy rules. Some proxy rules set Microsoft services to be directly connected. Modify them to use a proxy instead.

Thanks for your reply. EdgeGPT works again when I set Proxy.

**Comment by Silhouette6** [comment]
It was used for none proxy,but now......

**Comment by sigeryang** [comment]
rot13:
sha guvat vf gung bayl `/ghevat/pbairefngvba/perngr` arrqf cebkl naq punguho vf fgvyy npprffvoyr (ubcr guvf jba'g or svkrq ol Z$)

**Comment by VMTask** [comment]
How can not use proxy to work?

**Comment by DreamMaoMao** [comment]
> 它曾经用于无代理，但现在......
The reason I use this interface is because I don't want to use proxy ...

**Comment by acheong08** [comment]
> 如何搭建呢，反代吗

https://github.com/acheong08/EdgeGPT-Proxy

**Comment by acheong08** [comment]
- #194

**Comment by acheong08** [comment]
```bash
export BING_PROXY_URL="https://edge.churchless.tech/edgesvc/turing/conversation/create"
```

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.1.9

**Comment by acheong08** [comment]
It automatically retries on error with a public proxy server.

**Comment by wong2** [comment]
So does the fallback proxy have access to the user cookie? I think that should be clarified.

**Comment by acheong08** [comment]
It does in order to authenticate. How should I ensure transparency?

**Comment by acheong08** [comment]
It runs https://github.com/acheong08/EdgeGPT-Proxy and doesn't log anything

**Comment by wong2** [comment]
Maybe not provide it as a fallback, but let user use it manually via 
`export BING_PROXY_URL="https://edge.churchless.tech/edgesvc/turing/conversation/create"`

**Comment by wong2** [comment]
@acheong08 Can you add CORS headers to the proxy response? I'd like to use it in https://github.com/chathub-dev/chathub thanks!

**Comment by acheong08** [comment]
> @acheong08 Can you add CORS headers to the proxy response? I'd like to use it in [chathub-dev/chathub](https://github.com/chathub-dev/chathub) thanks!

Added

**Comment by acheong08** [comment]
> Maybe not provide it as a fallback, but let user use it manually via `export BING_PROXY_URL="https://edge.churchless.tech/edgesvc/turing/conversation/create"`

I want the experience to be smooth. Most people don't read the readme properly. You can of course still set `BING_PROXY_URL` to override it.

**Comment by Darkluna999** [comment]
> 我解决这个问题了! 把 https://edgeservices.bing.com/edgesvc/turing/conversation/create 改成我搭建的镜像站https://bing.vmtask.repl.co/edgesvc/turing/conversation/create 就行了。不过最好不要用我的，要自己搭建。

请问你是如何解决的？我自己部署之后会不断出现被新加坡微软云访问然后302。。。
![image](https://github.com/acheong08/EdgeGPT/assets/53258301/a506eb3e-5ba4-4258-89ed-a5628e2b6c0c)
头几个是直接浏览器访问和wget，没有任何问题
但使用python模块拉取就会触发302

**Comment by devinglaw** [comment]
出现故障！如果这个问题持续出现，请和我说“重置会话” 来开启一段新的会话，或者发送 “回滚会话” 来回溯到上一条对话，你上一条说的我就当作没看见。
CaptchaChallenge: User needs to solve CAPTCHA to continue.
