### ISSUE TITLE
Environment variable COOKIE_FILE doesn't work

### ISSUE THREAD

**Issue by xxr0ss** [acheong08/EdgeGPT#184]
I already set the COOKIE_FILE in path when I starts edgeGPT without additional args (`--cookie-file`)
```
PS> $env:COOKIE_FILE="$env:USERPROFILE\cookie.json" 
PS> python -m EdgeGPT

        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit

usage: EdgeGPT.py [-h] [--enter-once] [--no-stream] [--rich] [--style {creative,balanced,precise}]      
                  --cookie-file COOKIE_FILE
EdgeGPT.py: error: the following arguments are required: --cookie-file
```

I got the following error:
```
EdgeGPT.py: error: the following arguments are required: --cookie-file
```

**Comment by xxr0ss** [comment]
Thanks for your reply @joyspce.  I know `--cookie-file` works well, but I prefer setting COOKIE_FILE environment variable so that I do not need to type additional arguments every time.
I've opened https://github.com/acheong08/EdgeGPT/pull/185, it should fix this.

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.1.4
