### ISSUE TITLE
ImageGen error

### ISSUE THREAD

**Issue by youminxue** [acheong08/EdgeGPT#197]
![image](https://user-images.githubusercontent.com/3829455/227407047-bd6fcae4-fc23-439e-bf6c-fe2f05d3e412.png)

**Comment by youminxue** [comment]
![image](https://user-images.githubusercontent.com/3829455/227411762-4dbbdbd4-9e02-405e-9f2d-af5115332e5d.png)

**Comment by acheong08** [comment]
![1](https://user-images.githubusercontent.com/36258159/227412031-bf88c55c-165a-47ff-acb5-9bdcc2ccf6ad.jpeg)

**Comment by acheong08** [comment]
Can you try to debug and print the response text? (Requires git cloning the repo and changing a bit of code). I can't replicate it. Make sure you go on https://www.bing.com/images/create and check if it works. If it does, export new cookies from the page

**Comment by youminxue** [comment]
![image](https://user-images.githubusercontent.com/3829455/227415182-3b2b4a96-3026-4f62-af16-8c897493b1b6.png)
![image](https://user-images.githubusercontent.com/3829455/227415216-79df1eb4-e5b7-4227-9dc9-0ed85d142139.png)
![image](https://user-images.githubusercontent.com/3829455/227415280-2b6c90e0-ce09-4cbf-82a2-d4bc6acfce10.png)
![image](https://user-images.githubusercontent.com/3829455/227415354-ec581a03-5e80-4b98-bf6d-6b543d6eb0ad.png)
网站可以请求，cookie也是重新获取的打印了日志，status_code是200，response3.text返回第三幅图中的网页内容

**Comment by Do1e** [comment]
我遇到了相同的问题，不过访问 https://www.bing.com/images/create 重新导出一下cookie就好了

**Comment by youminxue** [comment]
@Do1e 访问https://www.bing.com/images/create 不会更新更新cookie中的_U数据吧？

**Comment by Do1e** [comment]
那可能需要退出之后重新登录一下吧。

**Comment by youminxue** [comment]
额，尝试重新登录后还不不行，使用最新的0.1.7版本也不行

**Comment by acheong08** [comment]
Blocked in China?

**Comment by youminxue** [comment]
是的，不过在国外服务器上也试过，同样的问题，edgeGpt的聊天功能正常

**Comment by acheong08** [comment]
Also getting same issue now. Will need to reverse again maybe

**Comment by acheong08** [comment]
Try new version

**Comment by doevent** [comment]
It has stopped working. Changing the IP and cookies does not solve the problem.

**Comment by shl-hsn** [comment]
Maybe it's because the number of drawing times has been used up！
Please open the URL: https://www.bing.com/images/create.
You can see the remaining times.
