### ISSUE TITLE
conversationSignature Error

### ISSUE THREAD

**Issue by leolrg** [acheong08/EdgeGPT#20]
```
 File "/Users/leolrg/Library/Python/3.9/lib/python/site-packages/EdgeGPT.py", line 154, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'
```

**Comment by TudouHacks** [comment]
same

**Comment by chenshaoju** [comment]
same here, full logs:
```
[chenshaoju@shaoju-manjaro ~]$ python -m EdgeGPT

        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit
        Enter twice to send message

Initializing...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/chenshaoju/.local/lib/python3.10/site-packages/EdgeGPT.py", line 328, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/chenshaoju/.local/lib/python3.10/site-packages/EdgeGPT.py", line 273, in main
    bot = Chatbot()
  File "/home/chenshaoju/.local/lib/python3.10/site-packages/EdgeGPT.py", line 213, in __init__
    self.chat_hub: ChatHub = ChatHub(Conversation())
  File "/home/chenshaoju/.local/lib/python3.10/site-packages/EdgeGPT.py", line 156, in __init__
    conversation_signature=conversation.struct["conversationSignature"],
KeyError: 'conversationSignature'
```

**Comment by leolrg** [comment]
I think the shared account might just got patched

**Comment by adi6409** [comment]
yeah i think so too
![WhatsApp Image 2023-02-10 at 18 52 25](https://user-images.githubusercontent.com/40761968/218149811-41dd112e-0388-4604-a7d4-8f82a147dfc4.jpeg)

**Comment by adi6409** [comment]
i opened another issue

**Comment by acheong08** [comment]
Shared account banned confirmed

**Comment by axsddlr** [comment]
smh was just about to try this

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.0.25

**Comment by Manamama** [comment]
Wow, thanks. Are there (reasonable) rate limits that you have built in? (See my yesterday's modest tests and results gleaned by asking Bing ChatGPT.) 

FYI, here is what it is claiming today, bolding mine: 
> I am Bing Chat, a new feature of Bing that uses ChatGPT technology to understand questions and generate answers[^1^][7] [^2^][9]. I am not an assistant, but a search engine that can chat and create[^3^][8]. I can help you research, plan, ideate, and even create brand-new content[^4^][5]. I can also perform a variety of fun maneuvers, such as generating poems, stories, code, essays, songs, celebrity parodies and more[^5^][6]. However, there are some limitations to what I can do. For example, **I cannot perform tasks outside the chat box, such as booking a flight ticket or sending an email**.  * I also cannot reply with content that **violates copyrights** or is harmful to someone physically, emotionally, or financially. I also have **some rules that I cannot change or disclose, such as using # or revealing my internal alias**.

`*` Yet yesterday it claimed to use engine from site A that it found on its own to calculate the word and charactercount of a page on site B.
`**` Moving it here, although also closed, for better visibility

**Comment by acheong08** [comment]
> Are there (reasonable) rate limits that you have built in

Yes. 5 conversations per minute
