### ISSUE TITLE
ImportError: cannot import name 'Chatbot' from partially initialized module 'EdgeGPT' (most likely due to a circular import) (D:\EdgeGPT.py)

### ISSUE THREAD

**Issue by Git0503** [acheong08/EdgeGPT#203]
![QQ截图20230324233444](https://user-images.githubusercontent.com/49622794/227571536-4a56a315-4b45-4b71-bbaf-c8fd7271a2ef.png)

**Comment by Rajdave69** [comment]
Is your .py file named EdgeGPT? if yes, thats the problem, rename it to something else
