### ISSUE TITLE
Exception: Authentication failed. You have not been accepted into the beta

### ISSUE THREAD

**Issue by DreamMaoMao** [acheong08/EdgeGPT#207]
![image](https://user-images.githubusercontent.com/30348075/227695651-c5111dc4-5717-4b6d-a130-53323272a2e7.png)

what happen?

**Comment by donglsci** [comment]
me too, wait for update

**Comment by DreamMaoMao** [comment]
this is a network problem,you have to change you vpn or use the latest EdgeGPT source code
