### ISSUE TITLE
httpx.ConnectTimeout: _ssl.c:975: The handshake operation timed out

### ISSUE THREAD

**Issue by VMTask** [acheong08/EdgeGPT#215]
Emm.The default proxy Url doesn't work.

**Comment by VMTask** [comment]
#214

**Comment by acheong08** [comment]
Is Cloudflare blocked in China as well?

**Comment by VMTask** [comment]
No, cloudflare is not prohibited, but its latency in China is very high, usually 200 ms+

**Comment by acheong08** [comment]
Do you have access to another CDN? I can share you the IP address for it to forward to. CDN needed to prevent DOS

**Comment by VMTask** [comment]
You can try gcore CDN.
