### ISSUE TITLE
The image resolution generated by imageGen is only half of the webpage's resolution.

### ISSUE THREAD

**Issue by DreamMaoMao** [acheong08/EdgeGPT#222]
![image](https://user-images.githubusercontent.com/30348075/227850567-34acb63b-01d2-48e1-991a-f5ec977d3eee.png)
![image](https://user-images.githubusercontent.com/30348075/227850661-a9f4c034-a47a-4387-87a4-ea70ea61bbe9.png)
Why is it that images generated on webpages have a resolution of 1024*1024, but those generated through imageGen are only half the resolution of the webpage?

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.1.11
