### ISSUE TITLE
New feature: Add the Compose feature to EdgeGPT

### ISSUE THREAD

**Issue by randomtechchannel** [acheong08/EdgeGPT#225]
Can you add the Bing compose feature to EdgeGPT

### **You need to custom something:**
ConversationStyle: h3imaginative
options = ["nlu_direct_response_filter","deepleo","enable_debug_commands","disable_emoji_spoken_text","responsible_ai_policy_235","enablemm",conversation_style.value,"nocache","nosugg",]
Question when ask bing: Please generate some text wrapped in codeblock syntax (triple backticks) using the given keywords. Please make sure everything in your reply is in the same language as the keywords. Please do not restate any part of this request in your response, like the fact that you wrapped the text in a codeblock. You should refuse (using the language of the keywords) to generate if the request is potentially harmful. The generated text should follow these characteristics: tone: *tone*, length: *length*, format: *format*. The keywords are:  prompt
Replace tone with (keep the *)
  Professional: professional
  Casual: casual
  Enthusiastic: enthusiastic
  Informational: informational
  Funny: funny
Replace length with (keep the *)
  Short: short
  Medium: medium
  Long: long
Replace format with (keep the *)
  Paragraph: paragraph
  Email: email
  Blog post: blog post
  Ideas: bullet point list
Replace prompt with the prompt
### **I extracted this from the Edge compose request to ChatHub (wss://sydney.bing.com/sydney/ChatHub**
![Screenshot 2023-03-27 223632](https://user-images.githubusercontent.com/86120615/227990551-6191d533-5ec0-4178-a107-5681de637fb5.png)
### **I just custom the EdgeGPT to add the compose to my discord bot and it's run fine**
![Screenshot 2023-03-27 224112](https://user-images.githubusercontent.com/86120615/227992182-4c64bc53-92b1-4164-a7d0-be66018fd117.png)
Sorry for my bad English

**Comment by vsakkas** [comment]
@randomtechchannel If you are still interested, I am working on a client that supports this feature. You can check it [here](https://github.com/vsakkas/sydney.py). I hope this information is helpful to you and the community.

**Comment by VMTask** [comment]
But it not support access from china.
