### ISSUE TITLE
raise exceptions.TimeoutError() from exc TimeoutError

### ISSUE THREAD

**Issue by Natural12349978** [acheong08/EdgeGPT#229]
app：termux（python3.11）
完整的报错图如下：
some wrong：
![Screenshot_20230328_160038_com termux](https://user-images.githubusercontent.com/117015081/228259037-46de2320-adba-4821-8e75-4950e369817d.jpg)
我在win下能正常使用（I can use it normally under Win）
这可能是python版本不同导致的，我还没来得及尝试（This may be due to different versions of Python, and I haven't had time to try yet）
我看到问题列表，也有可能是ipv6的问题导致的，我不敢确定，没有头绪，所以来提问，希望得到解答，谢谢各位（"I see a list of issues, which may also be caused by an issue with IPv6. I am not sure and have no clue, so I have come to ask questions and hope to receive answers. Thank you all."）

**Comment by VMTask** [comment]
请首先尝试`ping sydney.bing.com`，如无法请求超时，请关闭IPV6。
> Please first try `ping sydney.bing.com`,if timeout,please turn off ipv6.

**Comment by Natural12349978** [comment]
> 请首先尝试`ping sydney.bing.com`，如无法请求超时，请关闭IPV6。
> 
> > Please first try `ping sydney.bing.com`,if timeout,please turn off ipv6.

很奇怪的是，我后来又能用了，但是下午又不能用了2333

**Comment by Natural12349978** [comment]
> 请首先尝试`ping sydney.bing.com`，如无法请求超时，请关闭IPV6。
> 
> > Please first try `ping sydney.bing.com`,if timeout,please turn off ipv6.

termux里的终端ping sydney.bing.com是能ping通的。但可能确实是ipv6的问题，我用手机开热点进去好像更稳定。我有ipv6的检测网站。校园网是支持ipv6的，但是校园网也不是完全不能连接。也成功过。另外就是这个脚本现在使用的sydney.bing的接口嘛？之前好像不是，然后脚本寄了一段时间，我后来发现又能用了。好像有一个反向代理的脚本可以解决之前的问题，但是go语言不熟悉，命令行连接不上，全是超时

**Comment by VMTask** [comment]
那个是另外的问题，这个需要自己搭建对sydney.bing.com的反代，并在命令行加上`--wss-link`

**Comment by tianlichunhong** [comment]
为何是sydney.bing.com，www.bing.com不可以吗？或者说两者有什么区别吗？

**Comment by Natural12349978** [comment]
> 

当然有区别，之前访问的是bing的网址，但是被封了已经，无法访问，所以那段时间插件不能用，我还在好奇为什么现在又可以用了。看这个情况是换到sydney了。这个偏聊天，而不是搜索引擎。所以比较新的咨询你搜索不到。也不会像bingchat那样会有15（之前的数据）的对话次数限制然后要reset。想要访问原来的那个，可以参考另一个反向代理的用golang写的。运行完之后再在这边调用，虽然但是，那个golang的环境不太好装，直接命令行会超时，链接不到运行所用的工具

**Comment by Natural12349978** [comment]
我将关闭这个提问。解决方法是去掉ipv6的连接，并不要开启唤醒锁。在termux里运行依然会有一些问题，可以通过一些手段来解决，当然鉴于这个实在是太小众了。如果有人好奇可以私信来问我！
