### ISSUE TITLE
ASYNC not working.

### ISSUE THREAD

**Issue by KhawerAbbas7** [acheong08/EdgeGPT#25]
![Screenshot_20230210-192958](https://user-images.githubusercontent.com/85282172/218248948-e8159c00-1b1b-4765-8ad5-fd823838e245.jpg)
I am sorry that I am unable to share the error text

**Comment by acheong08** [comment]
What python version?

**Comment by KhawerAbbas7** [comment]
Python 3.10.8

**Comment by acheong08** [comment]
Do you have access to the new Bing waitlist? I can't test right now because shared account got suspended

**Comment by KhawerAbbas7** [comment]
No I am not, do i need an account for this?

**Comment by acheong08** [comment]
yes

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.0.25
