### ISSUE TITLE
We need more headers. Bing is going crazy

### ISSUE THREAD

**Issue by qust1n** [acheong08/EdgeGPT#254]
Hey! Please add the ability to change the HEADERS aka. user-agent. Bing algorithms are highly dependent on browser fingerprint, because of one fingerprint on many users, bing works like a demo version and sometimes goes crazy. The result is very different than the one in the official browser.

P.S. If you do, it would be very helpful to have instructions on how to get your right user-agent

**Comment by TonyJabbour** [comment]
i agree we need a way to change browser agent or headers...
