### ISSUE TITLE
new bing gives different answers when accessed through the web and through EdgeGPT

### ISSUE THREAD

**Issue by kettly1260** [acheong08/EdgeGPT#257]
I found that the responses from New Bing are inconsistent when accessed through web browsing and EdgeGPT. When using EdgeGPT to ask questions, I often receive the prompt "I'm sorry, I couldn't find any information about 'xxxx.' Can you provide more information so that I can better answer your question?" However, when accessing Bing through web browsing, it can provide answers normally or provide relevant explanations.

**Comment by notabene00** [comment]
Maybe you should try other `ConversationStyle`, like `creative`?
AFAIK, if it is instructed to be precise, it is afraid to hallucinate

**Comment by qust1n** [comment]
The answer depends a lot on the browser's HEADERS. You can change them in the main api file

**Comment by qust1n** [comment]
> Maybe you should try other `ConversationStyle`, like `creative`? AFAIK, if it is instructed to be precise, it is afraid to hallucinate

Change styles has nothing to do with it. I know how to change them and tested on the example of the same style

**Comment by kettly1260** [comment]
I can give the answer normally when I use the webpage, but EdgeGPT "Sorry, I can't answer your question." The replacement style cannot solve this problem
