### ISSUE TITLE
response = response['item']['messages'][1]['adaptiveCards'][0]['body'][0]['text']   error

### ISSUE THREAD

**Issue by Mrithul-E** [acheong08/EdgeGPT#258]
response = response['item']['messages'][1]['adaptiveCards'][0]['body'][0]['text']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^Open an interactive python shell in this frame
KeyError: 'messages'

**Comment by vsakkas** [comment]
`adaptiveCards` also contains citations links, so it can be useful, depending on the use case @wander303

**Comment by Mrithul-E** [comment]
very thanks!!
