### ISSUE TITLE
httpx.ConnectTimeout: _ssl.c:1091: The handshake operation timed out

### ISSUE THREAD

**Issue by HANiFLY** [acheong08/EdgeGPT#259]
I use the demo script as follows:
----------------------------------------------------------------------------------
import asyncio
from EdgeGPT import Chatbot, ConversationStyle
import json

async def main():
    with open('cookies.json', 'r') as f:
        cookies = json.load(f)
    bot = Chatbot(cookies=cookies)
    print(await bot.ask(prompt="Hello world", conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub"))
    await bot.close()

if __name__ == "__main__":
    asyncio.run(main())
----------------------------------------------------------------------------------
however, even I load the cookies.json and turn on the VPN, it still raises timeout error."httpx.ConnectTimeout: _ssl.c:1091: The handshake operation timed out"
What should I do?

Besides, the cookies I used seem to contain lost of records just like the following, is it normal?

[
    {
        "domain": ".bing.com",
        "expirationDate": 171299.409103,
        "hostOnly": false,
        "httpOnly": false,
        "name": "SRCH",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "DOB=20230403&T=1680533&POEX="
    },
    {
        "domain": "www.bing.com",
        "expirationDate": 16805098,
        "hostOnly": true,
        "httpOnly": false,
        "name": "ai_session",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "ZAYjnapNidR7K+ET|1671|16805308"
    },
]

**Comment by VMTask** [comment]
Public proxy is dead.Use my proxy:
```shell
export BING_PROXY_URL=https://edgegpt.zeabur.app/edgesvc/turing/conversation/create
```

**Comment by acheong08** [comment]
Public proxy DDOSed. I didn't notice

**Comment by acheong08** [comment]
> Public proxy is dead.Use my proxy:
> 
> ```shell
> export BING_PROXY_URL=https://edgegpt.zeabur.app/edgesvc/turing/conversation/create
> ```

Thank you

**Comment by VMTask** [comment]
This may be because there are many people in China using your service, unless multiple servers are used for streaming.

**Comment by acheong08** [comment]
The normal rate is 1 request / second. It suddenly jumped to over 30 / second which is weird. I blocked a useragent and everything is normal again
