### ISSUE TITLE
[maintenance] Consider to remove the image generator

### ISSUE THREAD

**Issue by frostming** [acheong08/EdgeGPT#265]
I found that the image generator code exists in both this repository and https://github.com/acheong08/BingImageCreator, and they are nearly identical. This is not ideal for maintenance due to the following reasons:

1. The bug fixes need to be released in both projects
2. Users may raise issues in both repos and be confusing

So, to reduce the confusion and repeating work, we can take one of the following actions:

1. Most radical, remove the image generator from this project and redirects users to the BingImageCreator project. This option addresses both issues above.
2. Change the image generator of this project to a dependency on BingImageCreator, this option can solve issue 1 but issue 2 still exists.

**Comment by acheong08** [comment]
> Change the image generator of this project to a dependency on BingImageCreator, this option can solve issue 1 but issue 2 still exists.

Will probably go this route
