### ISSUE TITLE
not working like a chat system

### ISSUE THREAD

**Issue by Mrithul-E** [acheong08/EdgeGPT#268]
i asked "hi" to EdgeGPT then i asked "what i asked" then it dont know that i asked _hi_ before that .why?

**Comment by Loui2** [comment]
Did you use the ChatBot.close() method? If you used the close() method for ChatBot class, then it would end the conversation and it would have no context on the previous messages sent to it.

**Comment by Mrithul-E** [comment]
does it works when i removed await bot.close()
