### ISSUE TITLE
newbing响应太慢了，有什么可以优化的方式吗

### ISSUE THREAD

**Issue by 404NotFound20** [acheong08/EdgeGPT#271]
newbing响应太慢了，有什么可以优化的方式吗

**Comment by HenMie** [comment]
无解，newbing原本就是有一个搜索的过程，你直接使用它的网页版也是很慢的，不过它在搜索是会弹出“正在搜索XXX”的提示，主观感受没那么明显。
No solution, Newbing originally has a search process, and even if you use its web version directly, it is also very slow. However, when searching, it will pop up a prompt saying "searching for XXX", which doesn't make the subjective feeling so obvious.
