### ISSUE TITLE
my one user sayed his name is xxx then my other user asked what is his name the it is saying that "xxx" how to solve that

### ISSUE THREAD

**Issue by Mrithul-E** [acheong08/EdgeGPT#275]
problem Eg:
my one user sayed his name is xxx then my other user asked what is his name the it is saying that "xxx" how to solve that

**Comment by VMTask** [comment]
Please display the code

**Comment by Mrithul-E** [comment]
# an object of WSGI application
import os
import re
from flask import Flask, make_response, render_template, request
from EdgeGPT import Chatbot, ConversationStyle
import asyncio


app = Flask(__name__)  # Flask constructor

bot = Chatbot(cookiePath=os.getcwd().replace("\\", "\\") + '/cookies.json')
async def bing_answer(question):
    global bot
    #bot = Chatbot(cookiePath=os.getcwd().replace("\\", "\\") + '/cookies.json')
    response = await bot.ask(prompt=question, conversation_style=ConversationStyle.creative,
                             wss_link="wss://sydney.bing.com/sydney/ChatHub")
    print(response)

    try:
        response = response['item']['messages'][1]['adaptiveCards'][0]['body'][0]['text']
    except:
        bot = Chatbot(cookiePath=os.getcwd().replace("\\", "\\") + '/cookies.json')
        response = await bot.ask(prompt=question, conversation_style=ConversationStyle.creative,
                             wss_link="wss://sydney.bing.com/sydney/ChatHub")
        response = response['item']['messages'][1]['adaptiveCards'][0]['body'][0]['text']      
    response = response.split("\n\n")
    source = "microsoft new bing ai"
    if len(response) >= 2:
        source = response[0]
        response.pop(0)
        response = " ".join(response)
    else:
        try:
            print("hi")
            response = response.replace("['", "").replace("']", "")
            response = response.replace('["', "").replace('"]', "")
        except:
            response = response[0]
            print(response)
    #await bot.close()
    return response, source


# A decorator used to tell the application
# which URL is associated function
@app.route("/ok")
def ok():
    return "hi"


@app.route("/")
def index():
    return render_template("index.html")


@app.route('/chat/<bing>')  # type: ignore
def hello(bing):
    ans, source = asyncio.run(bing_answer(bing))
    ans = re.sub(r"\[\^\d+\^\]", "", ans)  # remove anything that matches [^^number^^]
    ans = re.sub(r"\[\d+\]", "", ans)  # remove anything that matches

    return ans, source


@app.route('/ans', methods=['POST', 'GET'])  # type: ignore
def ans():
    if request.method == 'POST':
        user = request.form['nm']
        if user == "":
            user = "hi"
        user, source = hello(user)  # type: ignore
        source = re.sub(r"\[\d+\]:", "", source)  # type: ignore
        source = re.sub(r"\^\d+\^", "", source)  # type: ignore #
        source = str(source).split('\n')
        return render_template('index.html', ans=user, source=source)


if __name__ == '__main__':
    app.run(port=5500, debug=True)

**Comment by Mrithul-E** [comment]
`# an object of WSGI application
import os
import re
from flask import Flask, make_response, render_template, request
from EdgeGPT import Chatbot, ConversationStyle
import asyncio


app = Flask(__name__)  # Flask constructor

bot = Chatbot(cookiePath=os.getcwd().replace("\\", "\\") + '/cookies.json')
async def bing_answer(question):
    global bot
    #bot = Chatbot(cookiePath=os.getcwd().replace("\\", "\\") + '/cookies.json')
    response = await bot.ask(prompt=question, conversation_style=ConversationStyle.creative,
                             wss_link="wss://sydney.bing.com/sydney/ChatHub")
    print(response)

    try:
        response = response['item']['messages'][1]['adaptiveCards'][0]['body'][0]['text']
    except:
        bot = Chatbot(cookiePath=os.getcwd().replace("\\", "\\") + '/cookies.json')
        response = await bot.ask(prompt=question, conversation_style=ConversationStyle.creative,
                             wss_link="wss://sydney.bing.com/sydney/ChatHub")
        response = response['item']['messages'][1]['adaptiveCards'][0]['body'][0]['text']      
    response = response.split("\n\n")
    source = "microsoft new bing ai"
    if len(response) >= 2:
        source = response[0]
        response.pop(0)
        response = " ".join(response)
    else:
        try:
            print("hi")
            response = response.replace("['", "").replace("']", "")
            response = response.replace('["', "").replace('"]', "")
        except:
            response = response[0]
            print(response)
    #await bot.close()
    return response, source


# A decorator used to tell the application
# which URL is associated function
@app.route("/ok")
def ok():
    return "hi"


@app.route("/")
def index():
    return render_template("index.html")


@app.route('/chat/<bing>')  # type: ignore
def hello(bing):
    ans, source = asyncio.run(bing_answer(bing))
    ans = re.sub(r"\[\^\d+\^\]", "", ans)  # remove anything that matches [^^number^^]
    ans = re.sub(r"\[\d+\]", "", ans)  # remove anything that matches

    return ans, source


@app.route('/ans', methods=['POST', 'GET'])  # type: ignore
def ans():
    if request.method == 'POST':
        user = request.form['nm']
        if user == "":
            user = "hi"
        user, source = hello(user)  # type: ignore
        source = re.sub(r"\[\d+\]:", "", source)  # type: ignore
        source = re.sub(r"\^\d+\^", "", source)  # type: ignore #
        source = str(source).split('\n')
        return render_template('index.html', ans=user, source=source)


if __name__ == '__main__':
    app.run(port=5500, debug=True)
`

**Comment by VMTask** [comment]
Don't redefine the bot var every time.

**Comment by Mrithul-E** [comment]
i only defined that in the above of the async function
