### ISSUE TITLE
I cant get wss link, it gives me an error. How do i solve this?

### ISSUE THREAD

**Issue by Geskawary234** [acheong08/EdgeGPT#279]
I cant get wss link, it gives me an error. How do i solve this?
![изображение](https://user-images.githubusercontent.com/113011647/230791105-c2c48d8d-55f2-4301-8d93-3dbbdb379b3c.png)

**Comment by VMTask** [comment]
Update the EdgeGPT version,or wss_link is `wss://sydney.bing.com/sydney/Chathub`

**Comment by 50-Course** [comment]
Hello @Geskawary234 ,

It would seem you calling the module incorrectly, The module does provide an interface that needs a session link, for example: `--wss-link WSS_LINK   WSS URL(e.g. wss://sydney.bing.com/sydney/ChatHub)`.

For reference, refer to the ChatBot section of the readme here, [README](https://github.com/acheong08/EdgeGPT/blob/master/docs/README.md#chatbot)

**Comment by 50-Course** [comment]
> Update the EdgeGPT version,or wss_link is `wss://sydney.bing.com/sydney/Chathub`

👍🏼 give this a try

**Comment by Geskawary234** [comment]
> > Update the EdgeGPT version,or wss_link is `wss://sydney.bing.com/sydney/Chathub`
> 
> 👍🏼 give this a try

Well i acctually gave it a try, it works but when i made a telegram bot, there is like a minute or so of delay, and i kinda dont like it

**Comment by VMTask** [comment]
Use ask_stream for faster speed.If you don't like it,you can use ChatGPT.
