### ISSUE TITLE
KeyError: 'conversationSignature'

### ISSUE THREAD

**Issue by kaykouo** [acheong08/EdgeGPT#28]
It's working at the beginning, but after a while I got this error whenever I run EdgeGPT using command line or call the API

**Comment by acheong08** [comment]
Oh wow it just got suspended as well

**Comment by sfz009900** [comment]
@acheong08 KeyError: 'conversationSignature',I am the same. Did the account hang up?

**Comment by Manamama** [comment]
Cause [it got offended by my test jokes, see here](https://github.com/acheong08/EdgeGPT/issues/18#issuecomment-1426787390).

**Comment by taiyu2333** [comment]
I just wanted to try again, but I didn't expect it to fail so soon

**Comment by acheong08** [comment]
We got a new token

**Comment by acheong08** [comment]
Fixing now

**Comment by taiyu2333** [comment]
> 

I don't think you can do this, in case it fails again after an hour It is recommended to find a method for small-scale testing

**Comment by sfz009900** [comment]
@acheong08 You are a great man;)

**Comment by acheong08** [comment]
I'm adding more browser spoofing to make requests look normal

**Comment by acheong08** [comment]
It's done!

**Comment by sfz009900** [comment]
@acheong08 I saw it, but it seems to answer very slowly

**Comment by acheong08** [comment]
It's doing live internet searches so a bit slow

**Comment by sfz009900** [comment]
@acheong08 Ok, thank you very much indeed, so I can use it early, I've been waiting for 4 days haha

**Comment by wizerdo37** [comment]
Hi, how can i use this?

**Comment by acheong08** [comment]
> Hi, how can i use this?

Read readme

**Comment by wizerdo37** [comment]
> > Hi, how can i use this?
> 
> Read readme

Ok thank you

**Comment by acheong08** [comment]
> thanks for the quick fix! the command line is working now, but the API not yet, got a lot of errors and exceptions in the response

There are some quirks in the API to rate limit. You can reference the server code: https://github.com/acheong08/SydneyAuth/

**Comment by sfz009900** [comment]
@acheong08 It seems to be hanging again - -

**Comment by leolrg** [comment]
genuinely don't understand why it got patched even with the rate limit

**Comment by sfz009900** [comment]
@acheong08 It should be based on different IP to detect, in fact, you can make a relay server, all the other people's questions are sent to the bing api by this relay request

**Comment by acheong08** [comment]
I think there is a rate limit on their side, just undocumented

**Comment by acheong08** [comment]
> genuinely don't understand why it got patched this soon even with the rate limit

Because there was a huge number of users

**Comment by sooxt98** [comment]
@acheong08 im getting GET /auth HTTP/1.1" 502 166

**Comment by acheong08** [comment]
Yeah I've taken it down for now

**Comment by sfz009900** [comment]
@acheong08 You can limit each person to one question per minute to three minutes :(

**Comment by sfz009900** [comment]
@acheong08 Will you update it again? Dude

**Comment by acheong08** [comment]
Still getting limited

**Comment by acheong08** [comment]
I will update when I get new cookie

**Comment by sfz009900** [comment]
@acheong08 
Is the way you have it now sending cookies to everyone who uses EdgeGPT to request binging? Or does each person using EdgeGPT send the request to you and you send it to bing?

**Comment by sfz009900** [comment]
@acheong08 
I think a good way is for each person who uses EdgeGPT to send you a text message first, and then you forward it to bing

**Comment by taiyu2333** [comment]
Excuse me, can I still use it now
