### ISSUE TITLE
How can I solve this?

### ISSUE THREAD

**Issue by heyouwei2021** [acheong08/EdgeGPT#283]
I tried the example in spyder.
But I got this error!
RuntimeError: asyncio.run() cannot be called from a running event loop
How can I solve it?
Thank you.

**Comment by Mrithul-E** [comment]
what is your code

**Comment by heyouwei2021** [comment]
Thank you for responding.
My code is below:

import asyncio
import json
from EdgeGPT import Chatbot, ConversationStyle



async def main():
    #bot = Chatbot()
    with open('./cookies.json', 'r') as f:
        cookies = json.load(f)
    bot = Chatbot(cookies=cookies)
    print(await bot.ask(prompt="Hello world",
conversation_style=ConversationStyle.creative,
wss_link="wss://sydney.bing.com/sydney/ChatHub"))
    await bot.close()


if __name__ == "__main__":
    asyncio.run(main())

And the error is here.
 RuntimeWarning: coroutine 'main' was never awaited
  self.tb = tb
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):

  File
~\anaconda3\envs\cardata\lib\site-packages\spyder_kernels\py3compat.py:356
in compat_exec
    exec(code, globals, locals)

  File c:\users\heyouwei\code\car\untitled0.py:24
    asyncio.run(main())

  File ~\anaconda3\envs\cardata\lib\asyncio\runners.py:33 in run
    raise RuntimeError(

RuntimeError: asyncio.run() cannot be called from a running event loop
How should I solve it?

Mrithul-E ***@***.***> 于2023年4月10日周一 17:39写道：

**Comment by Mrithul-E** [comment]
try running that code using terminal
