### ISSUE TITLE
[Feature Request]: Is it possible to call the list of commands by "!" or hit "tab" key and use 'Enter' key submit?

### ISSUE THREAD

**Issue by PaTTeeL** [acheong08/EdgeGPT#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Like [revChatGPT](https://github.com/acheong08/ChatGPT). Is it possible to call the list of commands by "!" or "tab" key, and submit it by enter key?

![image](https://user-images.githubusercontent.com/9150277/230940851-129de53c-dcf0-4e25-be28-a3205f76d20c.png)

### Proposed workflow

1. Press 'Tab' key or enter '!' in the terminal.
2. Press Arrow/Tab key to select command.
3. Hit 'Enter' key to submit command.

**Comment by acheong08** [comment]
`alt+enter`

**Comment by PaTTeeL** [comment]
> `alt+enter`

It's ok. And could it possible to recognize commands miss typed enter behind it like below ?
```
!help

```
