### ISSUE TITLE
can anyone fix the "slow" issue of this by doing this

### ISSUE THREAD

**Issue by Mrithul-E** [acheong08/EdgeGPT#289]
**Q** :Your response is displayed word by word. Is it being sent from the server word by word or is the server sending the full response and the frontend JavaScript is making it appear word by word?

**ANS** : 
> bing website says "My responses are generated and sent as a whole from the server to your device" not word by word ,

 when get the whole response faster it will more faster know

**Comment by acheong08** [comment]
Server streams. It does not send the full response. I am not in control of the speed.

**Comment by s0md3v** [comment]
### My code (creative mode)
```python
bot = Chatbot(cookies=cookies)
reply = await bot.ask(prompt="When was the first spiderman comic published?", conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub")
print(json.dumps(reply, indent=4))
```

### Output using the library in CREATIVE mode
Spider-Man first appeared in the comic book Amazing Fantasy #15 in August 1962. It was written by Stan Lee and drawn by Steve Ditko. The comic was a huge success and led to an ongoing series that started in March 1963.

### Output from Bing Chat (browser) in CREATIVE mode
The answer is from web search results. The first Spider-Man comic was published in August 1962. It was called Amazing Fantasy #15 and it introduced the character of Peter Parker, a teenager who was bitten by a radioactive spider and gained superpowers. The comic book was written by Stan Lee and drawn by Steve Ditko. A copy of this comic book recently sold for $3.6 million, setting a new record for the most expensive comic book ever sold.

### Output from Bing Chat (browser) in PRECISE mode
The first Spider-Man comic was published in August 1962. It was called Amazing Fantasy #15 and was created by writer-editor Stan Lee and artist Steve Ditko.

## The Problem
I have run this test over 10 times and every time EdgeGPT's CREATIVE output looks more like Bing's precise mode. EdgeGPT produces short and precise answers despite being in CREATIVE mode.
