### ISSUE TITLE
please help!!

### ISSUE THREAD

**Issue by Mrithul-E** [acheong08/EdgeGPT#294]
not working as expected: 

### only function

`    async for message in bot.ask_stream(prompt=link, conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub"):
        sys.stdout.write(message[1]) 
        sys.stdout.flush()
        time.sleep(.4)`

**Comment by VMTask** [comment]
Fix then:
```
async for final,message in bot.ask_stream(prompt=link, conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub"): 
sys.stdout.write(message)  
sys.stdout.flush() 
time.sleep(.4)
```

**Comment by Mrithul-E** [comment]
response is coming but not this sys.stdout.flush()  working in vs code , power shell

**Comment by Mrithul-E** [comment]
`    async for final,message in bot.ask_stream(prompt=link, conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub"): 
             print(message, end='\r')  
             time.sleep(.4)`

also not working

**Comment by Mrithul-E** [comment]
> ` async for final,message in bot.ask_stream(prompt=link, conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub"):
 >print(message, end='\r') time.sleep(.4)` 
> also not working


https://user-images.githubusercontent.com/125123198/231660524-664a78c6-8945-49a4-a2d6-4222bc8151e5.mp4

**Comment by Mrithul-E** [comment]
why that is not working as i expected

**Comment by VMTask** [comment]
Oh,i forget it.
```
async for final,message in bot.ask_stream(prompt=link, conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub"):
if not final: 
sys.stdout.write(message)  
sys.stdout.flush() 
time.sleep(.4)
```

**Comment by VMTask** [comment]
You can view the EdgeGPT source code,you can find the example.

**Comment by Mrithul-E** [comment]
bot.ask() is very slow

**Comment by Mrithul-E** [comment]
yes

**Comment by Mrithul-E** [comment]
@VMTask i got the code :

```
wrote=0
    async for final, response in bot.ask_stream(
                    prompt=link,
                    conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub",
                ):
                    if not final:
                        print(response[wrote:], end="", flush=True)
                        wrote = len(response)
```

from source code
very thanks to all who replied in this issue
