### ISSUE TITLE
[Urgent] Bing has made some API Changes

### ISSUE THREAD

**Issue by s0md3v** [acheong08/EdgeGPT#299]
With my `ConversationStyle` set to `creative`, I was getting results with citations like we get with the `precise` style. I compared EdgeGPT's results to the actual Bing chat with various examples and I came to the conclusion that something's wrong with EdgeGPT.

By looking at the network logs in my browser for each conversation style on Bing, I found that the options are assigned to the respective style as follows:

```python
creative = "h3imaginative,clgalileo,gencontentv3"
balanced = "galileo"
precise = "h3precise,clgalileo"
```

Feel free to confirm it yourself but I think this is a minor but very important fix which should be prioritized.

**Comment by VMTask** [comment]
Ok,i will make a pull request.

**Comment by s0md3v** [comment]
Please re-open this. The issue still exists in `0.1.23`. Maybe there's some another factor which is affecting the output.

**Comment by acheong08** [comment]
What's the issue? Send screenshot examples

**Comment by s0md3v** [comment]
### My code (creative mode)
```python
bot = Chatbot(cookies=cookies)
reply = await bot.ask(prompt="When was the first spiderman comic published?", conversation_style=ConversationStyle.creative, wss_link="wss://sydney.bing.com/sydney/ChatHub")
print(json.dumps(reply, indent=4))
```

### Output using the library in CREATIVE mode
Spider-Man first appeared in the comic book Amazing Fantasy #15 in August 1962. It was written by Stan Lee and drawn by Steve Ditko. The comic was a huge success and led to an ongoing series that started in March 1963.

### Output from Bing Chat (browser) in CREATIVE mode
The answer is from web search results. The first Spider-Man comic was published in August 1962. It was called Amazing Fantasy #15 and it introduced the character of Peter Parker, a teenager who was bitten by a radioactive spider and gained superpowers. The comic book was written by Stan Lee and drawn by Steve Ditko. A copy of this comic book recently sold for $3.6 million, setting a new record for the most expensive comic book ever sold.

### Output from Bing Chat (browser) in PRECISE mode
The first Spider-Man comic was published in August 1962. It was called Amazing Fantasy #15 and was created by writer-editor Stan Lee and artist Steve Ditko.

## The Problem
I have run this test over 10 times and every time EdgeGPT's CREATIVE output looks more like Bing's precise mode. EdgeGPT produces short and precise answers despite being in CREATIVE mode.

**Comment by hanxu1355146559** [comment]
是的,我也发现了这个问题.同样使用创造模式.
当我希望他帮助我写一篇论文,使用EdgeGPT会告诉我:只可以给我大纲,具体的应该我自己写.
而当我用网页版,他会完整的帮我写出.

**Comment by VMTask** [comment]
So how can fix this issue?

**Comment by VMTask** [comment]
I'm in china mainland,So I can't use new Bing with browser.
I can't get the latest Bing's API.
Perhaps changing the header can work?

**Comment by VMTask** [comment]
I'm change the API request.
That question's answer in the new creative mode:
`Spider-Man's first comic appearance was in Amazing Fantasy #15, released in August 1962^1^ ^2^ ^3^. The comic was written by Stan Lee and  
drawn by Steve Ditko^2^ ^3^. It introduced the origin story of Peter Parker, a teenager who gained spider-powers after being bitten by a   
radioactive spider^2^ ^4^. The comic was a huge success and led to Spider-Man getting his own ongoing series, The Amazing Spider-Man, in   
March 1963^2^ ^4^.`

**Comment by VMTask** [comment]
If you don't wanna to try,you can try this beta one:[https://github.com/VMTask/EdgeGPT/tree/dev](https://github.com/VMTask/EdgeGPT/tree/dev).
Draw feature I'm WIP.

**Comment by hanxu1355146559** [comment]
我尝试了这个链接中的内容,依然有些问题.
比如,我需要他帮我写一篇文章,他确实答应了.但是并没有生成任何内容,或者说并没有将文章传递过来,仅仅将他自己的回话发送给我了.以下为内容
```You:
帮我写一个500字的关于生态文明建设的论文
Bot:
你好，这是必应。我可以尝试帮你写一个关于生态文明建设的论文，但是你需要告诉我一些具体的要求，比如论文的目的、观点、结构等。
You:
主题为关于生态文明建设与保护，用户范文展示。请直接开始写
Bot:
好的，我会尽力帮你写一篇关于生态文明建设与保护的范文。请看以下内容：
的范文。请看以下内容：
You:
请重新发文章发给我
Bot:
好的，这是我写的文章，请查收：
eature.```

**Comment by VMTask** [comment]
我说了是beta，没有完成

**Comment by acheong08** [comment]
I merged for testing. Not published

**Comment by VMTask** [comment]
目前看来可能还需要调用compose的API.

**Comment by VMTask** [comment]
> 帮我写一个500字的关于生态文明建设的论文

我不知道这是什么问题，但请在Bing.com上试试。
反正我这里官方也出不来。
![i5oWvE.png](https://i.328888.xyz/2023/04/23/i5oWvE.png)

**Comment by comienzo2093** [comment]
I still have the same issue with version 0.31.

```
async for data in bing_agent.ask_stream(raw=True, prompt=prompt, conversation_style=ConversationStyle.precise)
```
