### ISSUE TITLE
How to quickly join the whitelist

### ISSUE THREAD

**Issue by zengxiang1** [acheong08/EdgeGPT#3]

**Comment by acheong08** [comment]
Use Microsoft Edge

**Comment by leolrg** [comment]
>Use Microsoft Edge. They get priority

Phone or computer? Cuz in the "access being faster" they asked you to download the phone app and sign in on the phone app.

**Comment by acheong08** [comment]
Phone probably.
By the way: https://github.com/acheong08/EdgeGPT/releases/tag/0.0.10 allows you to access it without a cookie or authentication

**Comment by acheong08** [comment]
New release so you guys can access it while you wait for your own tokens

**Comment by leolrg** [comment]
ok thanks

**Comment by leolrg** [comment]
> New release so you guys can access it while you wait for your own tokens

```
 File "/Users/leolrg/Downloads/EdgeGPT/src/EdgeGPT.py", line 137, in __init__
    raise Exception(
TypeError: __init__() missing 3 required positional arguments: 'msg', 'doc', and 'pos'
```
Still not working in the new update?

**Comment by acheong08** [comment]
What did you try to do?

**Comment by acheong08** [comment]
`pip3 install --upgrade EdgeGPT`
`python3 -m EdgeGPT`

Don't try to run from the code directly

**Comment by acheong08** [comment]
> Is this program open source =>>bing.kpham.workers.dev worker.js

The source code was posted on Discord. It's just a basic proxy that injects a cookie. You aren't sharing any info with it so it's fine. It's only used to fetch conversation information

**Comment by acheong08** [comment]
It's around 20 lines of code

**Comment by acheong08** [comment]
> Calling this interface too many times per day will fail

Yes. Please don't abuse it

**Comment by zengxiang1** [comment]
thx
