### ISSUE TITLE
Every several hours (10 to 24) cookies expire or something...

### ISSUE THREAD

**Issue by notabene01** [acheong08/EdgeGPT#300]
And my bot just sends me this message:
<img width="477" alt="Screenshot 2023-04-15 at 02 01 50" src="https://user-images.githubusercontent.com/129467976/232168214-f76f95d9-3c49-4496-b35c-2fed5a7e07f3.png">.
But if I refresh cookies from the site, it will work again for the next 10-24 hours.
Cookies `expirationDate` is in two weeks and in a month for some of them.
Should I really change the cookies every ~10 hours?
Or what am I doing wrong?

**Comment by acheong08** [comment]
Expires if you log in again / use web browser

**Comment by notabene01** [comment]
So, please, guide me, what can I do to avoid it?
Log out in browser? 
Do not ever restart the script when runned, once I set new cookies?
<details><summary> Additional context </summary>
<p>
I made it a telegram bot, work in progress, so I need to restart it for testing purposes.
I've noticed that sometimes it works until you restart, and sometimes it just stops working, so to speak, the next morning.
I've never seen it work for more than a day without updating a cookies.
</br>
What happens when I restart the script? Why does it stop working?
Did cookies being updated while running script (in runtime)?
Maybe we then should save them back to file if it so? 
Then we can restart without such problems.
</p>
</details>

**Comment by hanxu1355146559** [comment]
You can use translation to understand.
我的建议是,你应该拥有两个Microsoft帐户,并同时申请New Bing.
其中一个帐户在 登陆、打开bing官网、获取cookie后粘贴到txt文本中,随后应立即退出此Microsoft帐户.
之后,将之前保存出来的包含cookie的txt文件存为json并按照要求保存至目录.
随后在自己设备的浏览器上登录自己的另一个帐户.
-----------------------------
以上的操作意义在于:为逆向工程提供一个专属的cookie,而平时通过自己设备浏览器使用的是另一个帐户,与服务器不冲突
我的操作,仅作参考.

**Comment by notabene00** [comment]
我将尝试这种方法并回来反馈，谢谢

**Comment by notabene00** [comment]
no, that didn't help. still logs off after no more than 12 hours

**Comment by notabene00** [comment]
Still relevant

**Comment by ynizon** [comment]
same probleme.

**Comment by notabene00** [comment]
@ynizon I created #378, like it if you still have to deal with it
