### ISSUE TITLE
Cookie file reading does not close file handle

### ISSUE THREAD

**Issue by peteh** [acheong08/EdgeGPT#315]
During unit testing the framework complains that not all file handles are closed. 
This is coming from the way the cookie file is read and there is no implicit or explicit close statement
```
        else:
            f = (
                open(cookiePath, encoding="utf8").read()
                if cookiePath
                else open(os.environ.get("COOKIE_FILE"), encoding="utf-8").read()
            )
```

Explicitly calling close or using the with statement would avoid the non-closed file handle
```
with open("hello.txt") as my_file:
    print(my_file.read())
```

This can become an issue if you have multiple instances and long running applications.

**Comment by acheong08** [comment]
What version are you on?

**Comment by acheong08** [comment]
I can't find that piece of code

**Comment by peteh** [comment]
You are right. This seems to have been fixed in the most recent version that uses the with statement. 

It was in the constructor of the Chatbot class. 

I should have tried the latest code before opening the issue. My bad.
