### ISSUE TITLE
it can't  work again

### ISSUE THREAD

**Issue by DreamMaoMao** [acheong08/EdgeGPT#319]
httpx connect timeout

when i use proxy,it always  tell me to login firest 

but i still can use in brower,it  isn't my account problem

and my cookie is latest

**Comment by DreamMaoMao** [comment]
这个报错是在linux平台的  我把linux上的EdgeGPT 卸载了  把win平台拷贝过去就可以了   linux 平台不可以直接pip install EdgeGPT使用

**Comment by kyle-kw** [comment]
> 这个报错是在linux平台的 我把linux上的EdgeGPT 卸载了 把win平台拷贝过去就可以了 linux 平台不可以直接pip install EdgeGPT使用



> 这个报错是在linux平台的 我把linux上的EdgeGPT 卸载了 把win平台拷贝过去就可以了 linux 平台不可以直接pip install EdgeGPT使用
请问直接拷贝过去的是那个版本？我使用的0.10.7版本，没有报错，但是好像在linux平台上，它变笨了。
