### ISSUE TITLE
Redirect failed Error on the ImgGen program

### ISSUE THREAD

**Issue by BarryAllen-Arrow** [acheong08/EdgeGPT#322]
as the title said.
it was working all just fine, and suddenly did this.....

**Comment by acheong08** [comment]
> as the title said. it was working all just fine, and suddenly did this.....

If it was working fine before, just make sure to update your cookies.

**Comment by BarryAllen-Arrow** [comment]
I've tried that, but it didn't work. The _U in the cookies seem to be the same as before

**Comment by hakersoft** [comment]
This is most likely an ip ban. I had this 2 times, I changed the IP on the hosting and it started working. Perhaps this is due to a large number of requests, for example, I have a bot for friends in telegram, and they draw 1000+ images daily

**Comment by cameronj86** [comment]
Hmmm getting the same error on my first time utilizing image gen

**Comment by OlegRuban-ai** [comment]
I also get this error, is there any solution for this?

**Comment by shirubei** [comment]
same here

**Comment by acheong08** [comment]
`pip install --upgrade BingImageCreator`?

**Comment by shirubei** [comment]
> `pip install --upgrade BingImageCreator`?

No, it won't work.  I installed this module today (just before the comment posted)

**Comment by acheong08** [comment]
I'll need to tweak some code to pass in all cookies probably

**Comment by acheong08** [comment]
I got an issue on async version but worked on normal. I'll try to debug

**Comment by acheong08** [comment]
https://github.com/acheong08/BingImageCreator/releases/tag/0.4.0

**Comment by acheong08** [comment]
https://github.com/acheong08/BingImageCreator/releases/tag/0.4.1

**Comment by acheong08** [comment]
broke sync when fixing async lol

**Comment by shirubei** [comment]
Got images successfully after changing to  "allow_redirects".
Thank you !
