### ISSUE TITLE
跟 https://www.bing.com/new 不是同一个？ 

### ISSUE THREAD

**Issue by macheal** [acheong08/EdgeGPT#323]
首先感觉不是很聪明

Q:你的版本号是多少？
A:你好，这是必应。我的版本号是 1.0.0。😊

Q:那你最新的发布时间是那天？
A:我的最新发布时间是 2023 年 4 月 1 日。😊

Q:那你和 https://www.bing.com/new 是同一个吗？
A:不，我和 https://www.bing.com/new 不是同一个。那个是必应的新版网页搜索，而我是必应的聊天模式。😊

**Comment by VMTask** [comment]
你使用的是什么对话风格?我正在尝试使EdgeGPT的对话风格和网页版一样。

**Comment by VMTask** [comment]
确实，现在确实有这个问题

**Comment by VMTask** [comment]
第三个问题网页也是同样的回答

**Comment by hanxu1355146559** [comment]
https://github.com/Soulter/QQChannelChatGPT
你可以看一下这个项目,这个项目是QQ机器人,而我似乎觉得这个QQ机器人更接近bing网页版,你可以尝试参考这个项目进行实验
