### ISSUE TITLE
0.2.0 import error

### ISSUE THREAD

**Issue by qust1n** [acheong08/EdgeGPT#325]
from EdgeGPT import Chatbot, ConversationStyle
...

>>>
ImportError: cannot import name 'ConversationStyle' from 'EdgeGPT' (/data/data/com.termux/files/usr/lib/python3.11/site-packages/EdgeGPT.py)

**Comment by acheong08** [comment]
Oops https://github.com/acheong08/EdgeGPT/releases/tag/0.2.1
