### ISSUE TITLE
EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service.

### ISSUE THREAD

**Issue by ronrozenberg** [acheong08/EdgeGPT#329]
I tried anything I could think of, but this still dosen't work. I am signed into my Microsoft account. Can anyone help?

**Comment by cande1gut** [comment]
@ronrozenberg You need get the cookies out of the Edge browser. You can do it directly from that browser or you can install an add-on such as [User-Agent Switcher and Manager](https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg) for Chrome. When installed, you have to use it to change the browser to Edge and export the cookies. You can do it manually or optionally with another add-on like [Cookie-Editor](https://chrome.google.com/webstore/detail/cookie-editor/hlkenndednhfkekhgcdicdfddnkalmdm) for Chrome.

**Comment by ronrozenberg** [comment]
Hey, the cookies were extracted from Edge.

**Comment by ronrozenberg** [comment]
I did extract the cookies from github

**Comment by cande1gut** [comment]
Could be that you are not correctly loading the cookies.

**Comment by ronrozenberg** [comment]
Well I set up an environment variable (windows) pointing out to the cookies file. Tried to change it, once signed in, once not, once through chrome but still the same error each time.

**Comment by WangYijun-OUC** [comment]
did u fix that？I still got that problem.

**Comment by ronrozenberg** [comment]
Nope.

**Comment by WangYijun-OUC** [comment]
I just export my JSON using edge instead of Chrome, find that there are some differences, and it work.

**Comment by acheong08** [comment]
It won't work from Chrome. Cookies should come from Edge.

**Comment by ronrozenberg** [comment]
But the cookies are from Edge........

**Comment by acheong08** [comment]
Are you signed in to multiple Microsoft accounts?

**Comment by acheong08** [comment]
Try clearing your cookies and logging in again

**Comment by ronrozenberg** [comment]
I will try again later and if it doesn't work I will try on a windows vm to see if my computer is the problem

**Comment by jihanyang** [comment]
You need to specify your cookie_path in Chatbot such as `bot = Chatbot(cookie_path='./cookies.json')`

**Comment by ronrozenberg** [comment]
Thanks that fixed it :D

**Comment by beijingtl** [comment]
Same issue for me. I login with Edge again and export a new cookie setting, then copy to the COOKIE_FILE, and it works. All the reasons is cookie information expire, you have to update it manually. Hope it workds for U.

**Comment by jl5770** [comment]
I am having this issue as well, but seemingly at random: I will get the `EdgeGPT.NotAllowedToAccess: Sorry, you need to login first to access this service.` error, sometimes several times in a row, but then it will work about 1/3 of the time (without making any changes to the cookie file). Any idea what could be causing this? Sorry, I am a very amateur programmer without a lot of experience

**Comment by cameronj86** [comment]
One thing that _I think_  helped me and could make a difference for others is to ensure you are logged in when you grab the cookie info. 

Initially, I wasn't logged in and in that context, the 'please login first' portion of the error message makes more sense
