### ISSUE TITLE
error last update 🛠

### ISSUE THREAD

**Issue by BlackDicky** [acheong08/EdgeGPT#332]
TypeError: 'NoneType' object is not subscriptable
Task was destroyed but it is pending!
task: <Task pending name='Task-221' coro=<<async_generator_athrow without __name__>()> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x10407c750>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x103f01470>, 6067.780540833), (<aiohttp.client_proto.ResponseHandler object at 0x103f00e50>, 6075.925487625)]']
connector: <aiohttp.connector.TCPConnector object at 0x10407c550>

**Comment by BlackDicky** [comment]
Update: besides this error, I noticed that writing "python3 EdgeGPT.py --style creative" asks to insert the "cookie.json" even though both the .py file and the .json file are in the same folder and even though I type "python3 EdgeGPT.py --cookie-file cookie.json" still gives an error.

**Comment by BlackDicky** [comment]
![Screenshot_20230424_002958_Termux](https://user-images.githubusercontent.com/100368940/233869640-c7c77be9-6acd-4cc6-9201-184cd34f570e.jpg)
![Screenshot_20230424_003015_Termux](https://user-images.githubusercontent.com/100368940/233869642-a9bb7d3e-04dc-4192-870e-1aefef67bf37.jpg)
![Screenshot_20230424_003026_Termux](https://user-images.githubusercontent.com/100368940/233869643-1d79d46a-bdae-4c7e-ab2c-9d88f29e6c3b.jpg)
![Screenshot_20230424_003033_Termux](https://user-images.githubusercontent.com/100368940/233869645-f3ca13a0-433c-4e80-969b-163ad6c03a4e.jpg)

**Comment by VMTask** [comment]
What is your python version and internet country?I don't have this error.

**Comment by VMTask** [comment]
And what is your EdgeGPT version?Is the image creator update?This error has nothing to do with that PR.

**Comment by hanxu1355146559** [comment]
我这里也报错
```
File "/.../.../EgdeGPT.py",line 10, in <module>
    import aiohttp
ModuleNotFoundError: No module named 'aiohttp'
```
并且我认为这个项目并不是网页版new bing.如果想使用网页版可以参考这个项目
https://github.com/Soulter/QQChannelChatGPT
他是QQ机器人,但他包含了New bing逆向工程,且他的New bing更贴近于网页版Bing的体验

**Comment by acheong08** [comment]
This is a genuine issue. Please downgrade to the previous version

**Comment by acheong08** [comment]
It works with simple tests but fails when web searching is involved

**Comment by VMTask** [comment]
> 我这里也报错
> 
> ```
> File "/.../.../EgdeGPT.py",line 10, in <module>
>     import aiohttp
> ModuleNotFoundError: No module named 'aiohttp'
> ```
> 
> 并且我认为这个项目并不是网页版new bing.如果想使用网页版可以参考这个项目 https://githubfast.com/Soulter/QQChannelChatGPT 他是QQ机器人,但他包含了New bing逆向工程,且他的New bing更贴近于网页版Bing的体验

```
pip install aiohttp
```

**Comment by BlackDicky** [comment]
@VMTask python version 3.11.1 edgegpt versione 0.3.0

**Comment by BlackDicky** [comment]
> Funziona con semplici test ma fallisce quando è coinvolta la ricerca sul web

Exactly

**Comment by KamiPasi** [comment]
> 

你说的这个项目用的也还是EdgeGPT这个项目啊

**Comment by lavilao** [comment]
downgrading to 0.2.1 fixes it

**Comment by BlackDicky** [comment]
Besides the little bug, I wanted to thank @acheong08 for this creation, you had a brilliant idea in creating this, well done guys, it's just the beginning of a great journey

**Comment by VMTask** [comment]
What should I do with the web content and reference sites of Bing search?

**Comment by yuanbaiqi** [comment]
Enter `alt+enter` or `escape+enter` to send a message

You:
硇洲岛旅游


Bot:
NoneTraceback (most recent call last):
  File "D:\workspace\EdgeGPT\src\EdgeGPT.py", line 704, in <module>
    main()
  File "D:\workspace\EdgeGPT\src\EdgeGPT.py", line 700, in main    
    asyncio.run(async_main(args))
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\a\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "D:\workspace\EdgeGPT\src\EdgeGPT.py", line 636, in async_main
    wrote = len(response)
            ^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

**Comment by acheong08** [comment]
> What should I do with the web content and reference sites of Bing search?

Print it out

**Comment by acheong08** [comment]
@yuanbaiqi Just downgrade

**Comment by VMTask** [comment]
Download the latest version.

**Comment by lavilao** [comment]
updated through pipx (if it matters) and it seems to be working fine now.

**Comment by VMTask** [comment]
@BlackDicky Update your EdgeGPT version,and try again.
