### ISSUE TITLE
Docker images not available

### ISSUE THREAD

**Issue by RichardoC** [acheong08/EdgeGPT#335]
Despite being pushed in https://github.com/acheong08/EdgeGPT/actions/runs/4779394393/jobs/8496447231 to GHCR, the images aren't being listed in the Packages link for this repo. 

Mind checking the permissions so I can use these docker images? The relevant page is likely to be https://github.com/users/acheong08/packages/container/EdgeGPT/settings which I don't have access to.

Thanks!

**Comment by ConnorJ** [comment]
I am running into a similar issue.

**Comment by acheong08** [comment]
Hmm I don't use docker much. Any idea what is causing the issue?

**Comment by acheong08** [comment]
It's definitely there https://github.com/users/acheong08/packages/container/package/edgegpt

**Comment by acheong08** [comment]
Oh seems to be a permissions issue

**Comment by acheong08** [comment]
![image](https://user-images.githubusercontent.com/36258159/236194475-e6762095-fffa-472f-9fe4-43db6c500596.png)

It shows up but I can't access from incognito. Any help would be appreciated

**Comment by acheong08** [comment]
Fixed
