### ISSUE TITLE
Bot answer varies between code request and actual Bing's chat

### ISSUE THREAD

**Issue by cande1gut** [acheong08/EdgeGPT#341]
I have been testing different requests and all the time I ask through code, the answer differs from the actual bot interface (While using the exact same words and same conversation style). Is there something I'm missing?

**Comment by VMTask** [comment]
You don't missing anything.

**Comment by cande1gut** [comment]
Thanks @VMTask, seems like a bot thing

**Comment by scmanjarrez** [comment]
I think this is normal, given how gpt works (probabilistic word selection). It should vary the response each time, no matter if you use Bing or EdgeGPT.

**Comment by VMTask** [comment]
> 

Sorry,I'm Chinese,so my English is bad.

**Comment by Jimlikespies** [comment]
I don't know if it's just me, I noticed there's a difference between the sidebar Bing chat and the web Bing chat, where the former tends to produce longer and more informal utterances (and better in role playing) while the latter one usually summarise content in a formal way and would actively avoid mentioning inappropriate stuffs in the context.

**Comment by scmanjarrez** [comment]
> I don't know if it's just me, I noticed there's a difference between the sidebar Bing chat and the web Bing chat, where the former tends to produce longer and more informal utterances (and better in role playing) while the latter one usually summarise content in a formal way and would actively avoid mentioning inappropriate stuffs in the context.

I think that's because of prone inject, they use it with compose as well (i.e. they insert certain keywords to generate different prompts). But take it with a grain of salt, I haven't inspected the requests.
