### ISSUE TITLE
How to change locale?

### ISSUE THREAD

**Issue by jasonz1360** [acheong08/EdgeGPT#342]
Hi,
I want to know how to change the locale to zh-CN, market to zh-US?

```
"locale": "en-us",
"market": "en-us",
"region": "us",
"messageId": "1e406a82-539c-4eef-87bd-f24f1519ae5f",
"requestId": "1e406a82-539c-4eef-87bd-f24f1519ae5f",
```

**Comment by VMTask** [comment]
Please change your code.The EdgeGPT.py file.

**Comment by VMTask** [comment]
What do you want?

**Comment by hennyschmidt** [comment]
I want to change the local, such that I get answers like I am using Bing Chat manually. I am Germany-based but the only results I get are US-us based

**Comment by VMTask** [comment]
#460
