### ISSUE TITLE
<rich.markdown.Markdown object at 0x0000022D8389B910>

### ISSUE THREAD

**Issue by Flyfish233** [acheong08/EdgeGPT#349]
#### System

Windows 11

`PSVersion                      5.1.22621.1037`
`BuildVersion                   10.0.22621.1037`
`CLRVersion                     4.0.30319.42000`

Python `WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0`

`EdgeGPT (0.3.1)`

#### Bug
![WindowsTerminal_OzDvThwElC](https://user-images.githubusercontent.com/37693645/235294713-ea1f4326-9cb3-4901-90fb-5acdb4653c1a.gif)

This happens every time if the user specifies **--rich** and outputs include Markdown.
After the bot outputs completely, all the text in the buffer will disappear and be replaced by two lines of `<rich.markdown.Markdown object at [Random]>`, which makes it impossible to use.

#### Outputs

`python -m EdgeGPT --cookie-file bing --rich`

You:
What is Markdown

Bot:
`<rich.markdown.Markdown object at 0x000001892048BB50>`
`<rich.markdown.Markdown object at 0x000001892048B340>`

**Comment by VMTask** [comment]
Yes, this bug still exists now, but without using this mode, there is no

**Comment by VMTask** [comment]
[https://github.com/acheong08/EdgeGPT/pull/351](https://github.com/acheong08/EdgeGPT/pull/351)

**Comment by VMTask** [comment]
没想到刚修一个Bug又出来一个

**Comment by Flyfish233** [comment]
> 没想到刚修一个 Bug 又出来一个

没事，坐等更新🥰

**Comment by VMTask** [comment]
现在应该已经可以了。
