### ISSUE TITLE
bug：Continuous dialogue is possible with“python3 -m EdgeGPT”, but not with Developer demo

### ISSUE THREAD

**Issue by alphaokxyz** [acheong08/EdgeGPT#350]

**Comment by VMTask** [comment]
The Developer demo requires you to write it yourself, and it is not included in the program.

**Comment by Diyago** [comment]
What do you mean write it yourself? How can I achieve continuous dialogue

**Comment by acheong08** [comment]
Just keep using the same Chatbot object
