### ISSUE TITLE
   bot = Chatbot(cookie_path='cookies.json')

### ISSUE THREAD

**Issue by djpapzin** [acheong08/EdgeGPT#353]
I keep getting this error when i run it: TypeError: Chatbot.__init__() got an unexpected keyword argument 'cookie_path'

**Comment by VMTask** [comment]
What's your command and version?Old version don't have this argument.

**Comment by djpapzin** [comment]
I am using this project: https://github.com/Ai-Austin/Bing-GPT-Voice-Assistant and it uses EdgeGPT==0.1.23

**Comment by VMTask** [comment]
Upgrade your version to EdgeGPT==0.3.1

**Comment by djpapzin** [comment]
I have upgraded, version 0.3.1 was the one giving me errors, the earlier versions seemed to work. I tried upgrading to 0.3.2, it's giving me the same error
