### ISSUE TITLE
Create conversation asynchronously

### ISSUE THREAD

**Issue by InterestingDarkness** [acheong08/EdgeGPT#355]

**Comment by VMTask** [comment]
你的问题是什么?
What's your issue?

**Comment by InterestingDarkness** [comment]
Make this async so it won't block GUI
https://github.com/acheong08/EdgeGPT/blob/351dbd0f3f07ed1b3fd87d24ad124cdd189b7eaf/src/EdgeGPT.py#L298
Maybe I'll make a PR for this later

**Comment by VMTask** [comment]
如果你要在GUI(如PyQt5/6)内使用，请使用多线程

**Comment by InterestingDarkness** [comment]
Multithreading is just ugly(too complex), single thread with async network request is just enough.

**Comment by VMTask** [comment]
You make it yourself.I don't wanna to try it.
