### ISSUE TITLE
Anti message revoke

### ISSUE THREAD

**Issue by InterestingDarkness** [acheong08/EdgeGPT#356]
I've already implemented this, and it has nothing to do with jailbreak
https://github.com/InterestingDarkness/EdgeGPT

**Comment by VMTask** [comment]
Default not is creative.It's balanced.The website also is balanced.
Why free sydney?If you free it,it will going crazy!
Restore the ImageGen.py.
It can't merge to the head.
I'll to try it.

**Comment by InterestingDarkness** [comment]
There will be another separate branch in my repo, including anti message
revoke only

2023年5月1日(月) 15:13 VMTask ***@***.***>:

**Comment by VMTask** [comment]
But something can merge to the head.

**Comment by VMTask** [comment]
[https://www.bilibili.com/read/cv23006229](https://www.bilibili.com/read/cv23006229)'s Uploader is you?

**Comment by InterestingDarkness** [comment]
> https://www.bilibili.com/read/cv23006229's Uploader is you?

No, I just want Bing spider to fetch the link
