### ISSUE TITLE
Python 3.7 support ?

### ISSUE THREAD

**Issue by manatlan** [acheong08/EdgeGPT#357]
Hi ... could it be possible to let it be compatible with python 3.7 (raspbian python version) ?
Thanks in advace

I could make a pr

**Comment by acheong08** [comment]
No. Won't be supported. You can upgrade your Python version

**Comment by tiansztiansz** [comment]
Hi, I'm also looking to run the project with python3.7, I found the answer at [this link](https://stackoverflow.com/questions/61206437/importerror-cannot-import-name-literal-from-typing).


```python
from typing import Literal
```
change to:
```python
try:
    from typing import Literal
except ImportError:
    from typing_extensions import Literal
```
