### ISSUE TITLE
[Feature Request]: Reverse engineered API of "https://chat.openai.com/" 

### ISSUE THREAD

**Issue by prairiewolf11** [acheong08/EdgeGPT#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

EdgeGPT is great idea,I make a robot with it,but it reacts slowly.
Openai API is also slow and not for free.
But "https://chat.openai.com/" is free and faster than openai's API and edgeGPT.

If it possiable to make a GPT from "https://chat.openai.com/" ?

It seems have same procedure of edgeGPT.

**Comment by acheong08** [comment]
https://github.com/acheong08/ChatGPT

**Comment by prairiewolf11** [comment]
Great .
Great.
