### ISSUE TITLE
[Bug]: expiring cookies every several hours

### ISSUE THREAD

**Issue by notabene00** [acheong08/EdgeGPT#378]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I used to use this project as an underlying library for a telegram bot.
And can't, because of cookies expiration or something every 10 to 24 hours.
Despite the fact that the real expiration_date they have from 2 weeks to a month from the current.

### Steps to reproduce the problem

1. download-install this project
2. put cookies to cookies.json and run
3. use a fully working project
4. wait/use it for a day
5. get error like "you've not accepted to the beta" or smth
6. renew cookie
7. restart service
seven circles of hell

### What should have happened?

Working project/tg-bot/them all for as long as cookies should be valid (until their expiration date)

### Version where the problem happens

latest

### What Python version are you running this with?

3.9.2

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
no, I am using instance of `Chatbot` class in my code and retrieving response via async generator
```

### Console logs

```Shell
just an error that I am not accepted to the beta
but working fine again for a day when I renew the cookies
```

### Additional information

I don't think the above is insufficient.

**Comment by comienzo2093** [comment]
same problem

**Comment by notabene00** [comment]
Still the same

**Comment by ElSnoMan** [comment]
I'm not experiencing this, so I'm curious what the difference is. Here's my environment details:

- MacBook Pro (M1) with Ventura `13.3.1`
- `edgegpt = "^0.3.6"`
- Python `3.10.1`

In my case, I created a simple ContextManager to handle closing and whatnot:

```python
class BingChat:
    """ContextManager for Bing Chatbot

    Usage:
        ```
        async with BingChat("path/to/cookies.json") as bot:
            response = await bot.ask(prompt="Tell me a joke", conversation_style=ConversationStyle.precise)

        print(response)
        ```
    """

    def __init__(self, cookies_path: str):
        self.cookies = load_cookies(cookies_path)

    async def __aenter__(self):
        self.bot = await Chatbot.create(cookies=self.cookies)
        return self

    async def ask(
        self,
        prompt: str,
        wss_link: str = "wss://sydney.bing.com/sydney/ChatHub",
        conversation_style: CONVERSATION_STYLE_TYPE = None,
        options: dict = None,
        webpage_context: str | None = None,
        search_result: bool = False,
    ) -> Dict:
        """Ask a question to the bot and return its response"""
        response = await self.bot.ask(prompt, wss_link, conversation_style, options, webpage_context, search_result)
        return response["item"]["messages"][1]["text"]

    async def __aexit__(self, exc_type, exc_value, traceback):
        await self.bot.close()
```

Example usage of this that is working for me:

```python
async def main():
    # 1. Get the code text from a file
    code = Path("examples/plans.component.html").read_text()

    # 2. Ask the bot to generate new code using the existing file
    async with BingChat("cookies.json") as bot:
        response = await bot.ask(prompt=TESTID_PROMPT.format(code), conversation_style=ConversationStyle.precise)

    # 3. Extract only the code
    completion = _extract_code_from_completion(response)

    # 4. Do something with the new code (ie save it to a file)
    console.print(completion)


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by yuanyanhui** [comment]
Same problem. Have to update the cookies.json file after a few hours.
@ElSnoMan In your solution, you used a context manager without changing anything to the cookies. Think the problem is about how the cookies are sent. Wondering how a context manager would help?

**Comment by notabene00** [comment]
@yuanyanhui Wholeheartedly agree. The above context manager has nothing to do with cookie management.

**Comment by notabene00** [comment]
In the meantime, it looks like somehow I've solved my problem. 
At least my script has been running for two days and continues to do so.
This issue should persist until we can recognise root cause, because, as we know now, this is not an isolated incident.

_Important: I have **NOT** changed any code relating to cookies._

Single clue: I've deleted Bing app from my iPhone. 
I haven't run it for a long time - just had it installed.
Don't know if it is related. I don't have any other thoughts yet.
We must get to the bottom of this. I'm in.

**Comment by ElSnoMan** [comment]
> Same problem. Have to update the cookies.json file after a few hours. @ElSnoMan In your solution, you used a context manager without changing anything to the cookies. Think the problem is about how the cookies are sent. Wondering how a context manager would help?

That's my point! I didn't say the Context Manager solved the problem 😅. I said that "I'm not experiencing the same issue and I've had the same `cookies.json` file for a long time now. Also, look at my code so you see that I'm not doing anything fancy or changing the cookies and it's working for multiple days."

Now, since then, I added some logic to my `load_cookies()` function because I didn't want to have to remember to _re-download_ the cookies every 30 days or so:

```python
def load_cookies(cookies_path: str) -> List[Dict]:
    path = Path(cookies_path)
    if not path.exists():
        raise FileNotFoundError(f"Could not find cookies file at {cookies_path}")

    with path.open() as file:
        cookies = json.load(file)

    # Add 30 days to today's date and set as expiration date
    thirty_days = 2592000
    expiration = "expirationDate"

    for cookie in cookies:
        if cookie.get(expiration):
            cookie[expiration] = datetime.now().timestamp() + thirty_days

    return cookies
```

NOTE: It was working for me _before_ this. It sounds like @notabene00 got it resolved, but I was trying to help find the root issue. It'd be different if everyone was experiencing the same issue. So maybe it's a Bing or EdgeBrowser issue? I'm not sure

**Comment by acheong08** [comment]
No more cookies required

**Comment by comienzo2093** [comment]
> No more cookies required

wow
