### ISSUE TITLE
[Bug]: Can't create image.

### ISSUE THREAD

**Issue by VMTask** [acheong08/EdgeGPT#380]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When i ask bing:create an image xxx.
It will answer this:
'adaptiveCards'
I'll try to create that.

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

Create image and print it out.

### Version where the problem happens

python3 -m EdgeGPT --cookie-file cookies.json --style creative --rich

### What Python version are you running this with?

Python 3.11.3

### What is your operating system ?

Android

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit

Initializing...
Enter `alt+enter` or `escape+enter` to send a message

You:
create an image:a tree

Bot:
'adaptiveCards'
I'll try to create that.
```

**Comment by ce4p99** [comment]
me too
