### ISSUE TITLE
[Feature Request]:  Consider adding something like the attached helper class

### ISSUE THREAD

**Issue by PFython** [acheong08/EdgeGPT#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

First of all thanks so much for sharing such a valuable tool - it's really helped me!  In the spirit of giving back, I wonder if the attached helper class would be worth including in the repo, especially to get new users up and running quickly?  It basically provides a wrapper and a way of quickly getting common results from the output of a query/prompt.

### Proposed workflow

Please see Pull Request https://github.com/acheong08/EdgeGPT/pull/396

**Comment by acheong08** [comment]
Duplicate of #396
