### ISSUE TITLE
【推荐】快速注册ChatGPT教程

### ISSUE THREAD

**Issue by hardwellwell** [acheong08/EdgeGPT#39]
SPAM

**Comment by Manamama** [comment]
It is a spam, commercial, against TOS (many) etc. Also untrue ;) , as one CAN se free virtual non-Chinese  #s for this.

Let us remove this pseudo isssue.

GTrans:
> On the payment page, fill in 1 for the payable amount , charge 1 USD, then click the [Payment] button, and scan the QR code to pay on the Alipay page that pops up (I won’t take a screenshot here)....
