### ISSUE TITLE
error message 报错

### ISSUE THREAD

**Issue by kamanqi** [acheong08/EdgeGPT#399]
![image](https://github.com/acheong08/EdgeGPT/assets/13653035/10219ada-fcb1-4b81-9fe6-0a6d2b636f82)
试了好几个版本 都会跳message错误 凡是以EdgeGPT为基础的几个github项目都有这个问题 很奇怪 有人知道怎么解决吗？

**Comment by VMTask** [comment]
CLI界面完整log发出来，就凭这个无法看出任何问题

**Comment by VMTask** [comment]
你选的是破解Sydney的prompt,你看看你是不是被封号了

**Comment by The---onE** [comment]
https://github.com/acheong08/EdgeGPT/issues/374 应该和这个报错是一个选择 抛出的异常就是'message'
