### ISSUE TITLE
[Feature Request]: The bot has no memory like the original

### ISSUE THREAD

**Issue by KyozuFR** [acheong08/EdgeGPT#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

How to make sure that the messages are related to the former prompt. I tried to do it artificially but bing limits it to 2000 characters. I'm not sure how to do this because the session closes at the end of the function.

### Proposed workflow

idk ^^

**Comment by OmarHedeya95** [comment]
Same issue. Any help?

**Comment by camAtGitHub** [comment]
Possibly helpful for acheong08 or people developing a fix...  
If you goto www.bing.com/chat > Click Ask-Me-Anything > then inspect elements (DevTools)  
There is variable `maxlength` set to 2000 changing it up to a maximum of 25000 does allow for larger inputs. (Worked via Edge browser when I tested it).

**Comment by acheong08** [comment]
![image](https://github.com/acheong08/EdgeGPT/assets/36258159/5887fb87-8903-4189-8a16-988a81cf9512)

Make sure to keep using the same object when calling (which keeps track of the conversation)

**Comment by acheong08** [comment]
> Possibly helpful for acheong08 or people developing a fix... If you goto [www.bing.com/chat](http://www.bing.com/chat) > Click Ask-Me-Anything > then inspect elements (DevTools) There is variable `maxlength` set to 2000 changing it up to a maximum of 25000 does allow for larger inputs. (Worked via Edge browser when I tested it).

This I will look at

**Comment by OmarHedeya95** [comment]
> ![image](https://user-images.githubusercontent.com/36258159/239728617-5887fb87-8903-4189-8a16-988a81cf9512.png)
> 
> Make sure to keep using the same object when calling (which keeps track of the conversation)

Very interesting but how can I do that in code? Can you show an example please? Thanks a lot!
