### ISSUE TITLE
[Bug]: We're sorry — we've run into an issue. imagegen

### ISSUE THREAD

**Issue by raaaas** [acheong08/EdgeGPT#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

well, everything worked perfectly and from yesterday its not working , i can still work with chatbot but image gen just give me this error 

i updated cookies. and still not working and CHATBOT IS working fine . only imagegen not working  

### Steps to reproduce the problem

1. python3 -m ImageGen --cookie-file cookies.json --prompt help --output-dir ./outt

2. Press Enter
3. nothing happen 

### What should have happened?

well create image on outt folder 

### Version where the problem happens

i think on all version since got this error on earlier version so i updated to latest one and still got error 

### What Python version are you running this with?

3.9.2

### Command Line Arguments

```Shell
python3 -m ImageGen --cookie-file cookies.json --prompt help --output-dir ./outt
```

### Console logs

```Shell
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.9/dist-packages/ImageGen.py", line 11, in <module>
    main()
  File "/usr/local/lib/python3.9/dist-packages/BingImageCreator.py", line 375, in main
    image_generator.get_images(args.prompt),
  File "/usr/local/lib/python3.9/dist-packages/BingImageCreator.py", line 108, in get_images
    raise Exception(error_redirect)
Exception: Redirect failed
```

**Comment by VMTask** [comment]
If you are a Chinese?

**Comment by raaaas** [comment]
> If you are a Chinese?

no , i run it on my server on Germany .  and i can open image creator from my computer with no problem .

**Comment by raaaas** [comment]
its look like this new update fixed my problem thanks :)
