### ISSUE TITLE
[Feature Request]: Bing has made some API Changes

### ISSUE THREAD

**Issue by VMTask** [acheong08/EdgeGPT#402]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Update the API.Because Bing's API is changed.

### Proposed workflow

1. Go to ....
2. Press ....
3. ...

**Comment by teknium1** [comment]
bot still seems to work for me?

**Comment by VMTask** [comment]
yes.

**Comment by teknium1** [comment]
> yes.

Do you know what to do to make sure it uses gpt4

**Comment by InterestingDarkness** [comment]
According to my test result, only creative mode uses GPT-4

**Comment by VMTask** [comment]
Yes,But the API is changed.Who can change the API request?

**Comment by InterestingDarkness** [comment]
If it ain't broke, don't fix it

**Comment by AISIS7** [comment]
hello what's going on? it's working fine for me. what changes are you talking about?

**Comment by VMTask** [comment]
The webpage have add the history feature and UnAuthenticatedUsers also can use the New Bing's services.
Remove the required options:--cookie-file.
Add this command: `!load $FILENAME` and `!save $FILENAME`.
Details can view my project.

**Comment by acheong08** [comment]
Nice. I'll check this out

**Comment by teknium1** [comment]
> The webpage have add the history feature and UnAuthenticatedUsers also can use the New Bing's services. Remove the required options:--cookie-file. Add this command: `!load $FILENAME` and `!save $FILENAME`. Details can view my project.

Wait so anyone can use it without login now? Unlimited use?

**Comment by acheong08** [comment]
> > The webpage have add the history feature and UnAuthenticatedUsers also can use the New Bing's services. Remove the required options:--cookie-file. Add this command: `!load $FILENAME` and `!save $FILENAME`. Details can view my project.
> 
> Wait so anyone can use it without login now? Unlimited use?

Limitation is 5 messages/conversation iirc

**Comment by acheong08** [comment]
> Should make it so the cookies arent required but useable anyways for more chats.

That is already the case

> Is the current total chats/day limit still 100?

200

**Comment by manatlan** [comment]
I use 0.4.4 with a cookie file ... so it's the authenticated version.

Currently, I've got a 200requests per day.

The new one, without cookie file, will give me 5 requests/day ?!

I don't want to upgrade, it's a big regression for me ....

BTW: The readme.md should be more explicit. You should provide more examples, and explain more... The are lot of confusions.

**Comment by teknium1** [comment]
> I use 0.4.4 with a cookie file ... so it's the authenticated version.
> 
> Currently, I've got a 200requests per day.
> 
> The new one, without cookie file, will give me 5 requests/day ?!
> 
> I don't want to upgrade, it's a big regression for me ....
> 
> BTW: The readme.md should be more explicit. You should provide more examples, and explain more... The are lot of confusions.

No they are saying that if you dont use a cookie authentication that you will have 5/day but if you do its 200

**Comment by acheong08** [comment]
You can still authenticate with the new version

**Comment by manatlan** [comment]
@InterestingDarkness @acheong08 thanks for clarification ...

But how to use the authenticate new version (passing a cookie file, like on 0.4.4 doesn't seems to work now) ... There should be an example, to clarify that .. No ?

**Comment by acheong08** [comment]
You implement reading the cookie file yourself and pass it as a list[dict]

**Comment by acheong08** [comment]
Check wiki on create function

**Comment by VMTask** [comment]
Please reopen this.
