### ISSUE TITLE
[Feature Request]: Blazing Fast API

### ISSUE THREAD

**Issue by ayoubelmhamdi** [acheong08/EdgeGPT#405]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I have noticed that the local server API is much faster than the standard communication method. As a user, I prefer to work with a local server and avoid frequent communication with Gpt or starting new conversations from scratch. 
I like
```shell
cat file | edgebing | tee file.md
```
or C/CPP/LUA codes to achieve this.
I came across [Google-Bard-API](https://github.com/ra83205/google-bard-api) which offers a reversed API that utilizes a local server for improved efficiency. I would appreciate a similar feature for Bard in the future. Could you please consider adding this feature to enhance user experience and boost productivity? Thank you.

### Proposed workflow

use Python library called [fastapi](https://fastapi.tiangolo.com)

**Comment by acheong08** [comment]
API not planned.
