### ISSUE TITLE
[Feature Request]: Multi Prompt

### ISSUE THREAD

**Issue by arifengineer** [acheong08/EdgeGPT#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

is it possible to send multiple prompt ? will be good if it takes multiple prompts from Excel File and runs it prompts

### Proposed workflow

will be good if it takes multiple prompts from Excel File and runs it prompts

**Comment by acheong08** [comment]
You can do that easily with code. There is some library documentation.
