### ISSUE TITLE
[Question]:  Can wss_link="wss://sydney.bing.com/sydney/ChatHub" be ignored?

### ISSUE THREAD

**Issue by PFython** [acheong08/EdgeGPT#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I noticed that omitting `wss_link="wss://sydney.bing.com/sydney/ChatHub"` seems to have no effect in the `Chatbot.ask` method... in which case, can it be ignored and removed from the README altogether?

I haven't used or come across WSS Links previously so am puzzled and imagine there are other who read the same thing and wonder what it's all about?

Are there other values that can/should be used for different geographies?

### Steps to reproduce the problem

Update README

### What should have happened?

Either don't mention at all, or explain in README?

### Version where the problem happens

Version: 0.3.6

BTW the prompt in the issue for should presumably say `python -m pip show EdgeGPT` not `python3 -m pip show revChatGPT`?

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
N/A
```

**Comment by acheong08** [comment]
Readme updated. It was for Chinese users that needed to define a wss proxy
