### ISSUE TITLE
[Bug]: bad escape \m at position 11

### ISSUE THREAD

**Issue by thestark77** [acheong08/EdgeGPT#417]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

A few minutes ago, EdgeGPT library stopped working on my Python project, it can't catch a response, the only error information I get is "bad escape \m at position 11", I'm aware of 0.4.4 update, I already upgraded, generated the cookies.json file again from bing.com on Edge and re-read docs, but it seems to be good from my end.

I know you're working really hard on this project, no pressure, just wanted to notice you and, by the way, congratulate you for your awesome work 😊

### Steps to reproduce the problem

1. bot = await Chatbot.create(cookie_path='./settings/cookies.json')
2. response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative)
3. >> bad escape \m at position 11

### What should have happened?

I should get an object with bot's response

### Version where the problem happens

I've tested on 0.4.3 and 0.4.4

### What Python version are you running this with?

I've tested on 3.10.10 and 3.11.3 python

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
bad escape \m at position 11
```

**Comment by acheong08** [comment]
Windows? You guys have different paths iirc

Something like `\\.settings\\cookies.json`

**Comment by thestark77** [comment]
I guess it was a temporary error from bing, I just wait 1 hour, tried again and it worked normally, so, that's it, thanks a lot

**Comment by acheong08** [comment]
That's weird. I'll try to add some error handling

**Comment by thestark77** [comment]
Yes, so weird, sorry for the issue report, its closed now, thank you for your work and your patience :)
