### ISSUE TITLE
[Feature Request]: Save chat history to disk

### ISSUE THREAD

**Issue by camAtGitHub** [acheong08/EdgeGPT#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Save history (chats) to a file.

### Proposed workflow

1. Pass program `--history` or `--save` flag and chat history gets saved to ~/.edgeGPT/chats/foobar.log

### Additional information

Thanks for your effort to date...

**Comment by tom-snow** [comment]
In my opinion, if you using EdgeGPT like a api (call bing ai in your program), you do it in your program is better.
If you just using it in command line (like `python -m EdgeGPT ...`), save log may useful

**Comment by yvay** [comment]
I made a patch for this feature at https://github.com/yvay/EdgeGPT/commit/9f519cc5ae3273b139e16777d82a4a243ea517c7

It's a bit ugly but so far it seems to work for me. I will try to tidy it up and prepare a PR if that's okay. I would love to see this feature in EdgeGPT.
