### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by Harry-Jing** [acheong08/EdgeGPT#42]

**Comment by acheong08** [comment]
Will do

**Comment by hafidzaini** [comment]
+1

**Comment by lss233** [comment]
Consider using websocket-client instead of websockets?  

I notice that the issue for proxy support of websockets is open for 3 years.  https://github.com/aaugustin/websockets/issues/364  

websocket-client has full support to SOCKS proxy and HTTP proxy: https://pypi.org/project/websocket-client/
