### ISSUE TITLE
[Bug]:  Can't create the bot instance and  returns Exception: Throttled: Request is throttled (2 issues)

### ISSUE THREAD

**Issue by Mbonea-Mjema** [acheong08/EdgeGPT#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

The first issue is with the bot instance creation, it could be because of the headers. The GET request to https://edge.churchless.tech/edgesvc/turing/conversation/create does not return anything (but the link works on the browser). The other issue is "self.chat_hub.ask_stream"  returns Exception: Throttled: Request is throttled. I haven't even tried it

### Steps to reproduce the problem

Clone the project use  v0.6.2 and run the example script

### What should have happened?

1. It should have created a bot instance 
2. If the bot instance is created it throws "Exception: Throttled: Request is throttled"  when a promt is sent

### Version where the problem happens

 EdgeGPT-0.6.2

### What Python version are you running this with?

3.8.12

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
1. 
========== Can't create a bot instance=================================
    bot = await Chatbot.create()
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/EdgeGPT.py", line 629, in create
    await _Conversation.create(self.proxy, cookies=cookies),
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/EdgeGPT.py", line 402, in create
    raise Exception(
Exception: Authentication failed. You have not been accepted into the beta.



2.================================== Request is throttled====================================


  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/EdgeGPT.py", line 652, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "/home/gitpod/.pyenv/versions/3.8.12/lib/python3.8/site-packages/EdgeGPT.py", line 569, in ask_stream
    raise Exception(
Exception: Throttled: Request is throttled.
```

**Comment by acheong08** [comment]
> Exception: Throttled: Request is throttled.

Rate limited by Microsoft

**Comment by ElSnoMan** [comment]
Last I saw (March 29, 2023), the rate limit was:

* 20 Chats per Session
* 200 Chats per day

You can see from official tweets and articles such as this: https://www.seroundtable.com/bing-chat-remove-limits-35112.html

**Comment by Mbonea-Mjema** [comment]
> > Exception: Throttled: Request is throttled.
> 
> Rate limited by Microsoft

I didn't even do anything

**Comment by tom-snow** [comment]
If you are not using cookies, the limit may be related to your ip

**Comment by Mbonea-Mjema** [comment]
Cookies don't even work, I tried everything

**Comment by SinbadSails** [comment]
even when I cycle through json files, I get the requestthrottled error. Why is this happening in different instances?

**Comment by acheong08** [comment]
IP?

**Comment by ElSnoMan** [comment]
I'm now having this issue as well and I've just uninstalled it since I'm getting `JailBreak` errors from Bing. Looks like they're aware and putting in measures to prevent this kind of automation
