### ISSUE TITLE
Using without auth

### ISSUE THREAD

**Issue by acheong08** [acheong08/EdgeGPT#424]
### Discussed in https://github.com/acheong08/EdgeGPT/discussions/422

<div type='discussions-op-text'>

<sup>Originally posted by **Eikosa** May 22, 2023</sup>
How can I use it without authentication? I think it would be very nice if the documents were more detailed</div>

**Comment by acheong08** [comment]
It seems unauthenticated usage does not work in all cases.

**Comment by Eikosa** [comment]
Information about the situation where the problem occurred:
Ubuntu 22.10
Digital Ocean
**Version:** 0.6.2
**Python:** 3.10.9

**Comment by acheong08** [comment]
Seems to be a location based thing
