### ISSUE TITLE
[Bug]: Bing not responding after a while

### ISSUE THREAD

**Issue by Eikosa** [acheong08/EdgeGPT#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I talk from CMD using the command (python -m EdgeGPT), after a while it stops responding to anything I type.

### Steps to reproduce the problem

1. Talk many times without auth until error
3. See the error 

### What should have happened?

If the total dialog has ended, it should be restart the conversation.

### Version where the problem happens

0.6.2

### What Python version are you running this with?

3.10.9

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
python -m EdgeGPT
```

### Console logs

```Shell
You: 
What is the respiration rate of the patient in the question?

Bot:

You: 
What is the respiration rate of the patient in the question?

Bot:

```

**Comment by acheong08** [comment]
Without authentication, there is a 5 message limit on conversations. When authenticated, that should be around 20.

**Comment by acheong08** [comment]
Do `!reset` when it stops responding

**Comment by Eikosa** [comment]
Thank you, the automatic conversation reset might be a feature request then.
