### ISSUE TITLE
[Bug]: msg = await self.wss.receive() The code has a timeout waiting. 

### ISSUE THREAD

**Issue by zhengjie13** [acheong08/EdgeGPT#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Setting 30 seconds with timeout = aiohttp.ClientTimeout(total=30) does not work, 
the program will keep waiting and will not raise an exception or terminate the program. 
Changing it to msg = await asyncio.wait_for(self.wss.receive(), timeout=30) still does not work.

### Steps to reproduce the problem

1. bot = await Chatbot.create(proxy=proxystr,cookies=cookies)
2. backstr = await bot.ask(prompt=strv, conversation_style=ConversationStyle.creative)

### What should have happened?

msg = await self.wss.receive() 
The code keeps waiting for msg to return content, without raising an exception. It has been tested for 1 hour without returning an exception.

### Version where the problem happens

[0.6.3]

### What Python version are you running this with?

3.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
......................................................................................
```

**Comment by acheong08** [comment]
Timeout is specified by the receive call.

```python
msg = await self.wss.receive(timeout=10)
```

**Comment by zhengjie13** [comment]
WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')
.WSMessage(type=<WSMsgType.TEXT: 1>, data='{"type":6}\x1e', extra='')

**Comment by acheong08** [comment]
?

**Comment by tom-snow** [comment]
```
msg = await self.wss.receive(timeout=10)
```

logs:
![image](https://github.com/acheong08/EdgeGPT/assets/79245287/56e8a1dd-936d-4258-9424-52722d6e334e)

seems 10 seconds is too short ( specifically using with no cookie )
