### ISSUE TITLE
[Bug]: EdgeGPT 搜索不到结果，但网页版可以

### ISSUE THREAD

**Issue by LakeishaKowalczyk** [acheong08/EdgeGPT#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![图片](https://github.com/acheong08/EdgeGPT/assets/14090545/c0ab1130-5094-407c-96c1-ac502c68e4c0)
![图片](https://github.com/acheong08/EdgeGPT/assets/14090545/dc794018-f7cb-4716-ade4-4581e1eb0a0f)

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

与网页版提供相同的回复

### Version where the problem happens

EdgeGPT  0.6.5

### What Python version are you running this with?

Python 3.11.3

### Command Line Arguments

```Shell
python -m EdgeGPT --proxy http://127.0.0.1:7890 --style precise --prompt 长城公司举报比亚迪是什么事件
```

### Console logs

```Shell
python -m EdgeGPT --proxy http://127.0.0.1:7890 --style precise --prompt 长城公司举报比亚迪是什么事件

        EdgeGPT - A demo of reverse engineering the Bing GPT chatbot
        Repo: github.com/acheong08/EdgeGPT
        By: Antonio Cheong

        !help for help

        Type !exit to exit

Initializing...
Enter `alt+enter` or `escape+enter` to send a message

You:
长城公司举报比亚迪是什么事件

Bot:
我不知道这个事件。你能告诉我更多关于这个事件的信息吗？


You:
```

**Comment by VMTask** [comment]
#460
