### ISSUE TITLE
[Bug]: Query的参数已经修改为cookie_file了，但说明中还是cookie。另外使用过程中代码报错

### ISSUE THREAD

**Issue by iaston** [acheong08/EdgeGPT#448]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

   
![image](https://github.com/acheong08/EdgeGPT/assets/11807657/c316cfc3-35ec-49e5-b544-e5c04699ba24)
![image](https://github.com/acheong08/EdgeGPT/assets/11807657/64850a9a-bb59-4b95-a510-f0284d2db32d)

另外，Query不支持proxy参数吗？

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

正确运行

### Version where the problem happens

0.6.8

### What Python version are you running this with?

3.9

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
from EdgeGPT import Query, Cookie
import os
g_current_dir = os.getcwd()
ans = Query(question, style="balanced", cookie_file=g_current_dir + "/cookie_bing.json")
    print(ans)
```
```


### Console logs

```Shell
错误信息：
  File "D:\software\miniconda3\envs\....\Lib\site-packages\EdgeGPT.py", line 1028, in __init__
    if cookie_file in files():  # Supplied filepath IS in Cookie.dirpath
                      ^^^^^^^
TypeError: 'list' object is not callable
```

**Comment by acheong08** [comment]
CC: @PFython

**Comment by acheong08** [comment]
Also added proxy support.

There is something wrong with the implementation right now though. Cookies aren't being passed through to the Chatbot in Query

**Comment by acheong08** [comment]
@PFython Could you review the closing commit when you get the time? The Query and Cookie classes are a bit confusing to me

**Comment by PFython** [comment]
Sorry for the slow reply - yes this was just a copy/paste error and I see you've already corrected it from `files()` to `files`  Thanks!
