### ISSUE TITLE
[Bug]: 0.6.9 Cookie Error

### ISSUE THREAD

**Issue by iaston** [acheong08/EdgeGPT#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

    ans = Query(question, proxy=g_proxy, style="balanced", cookie_file="./cookie_bing.json")

error info:
  File "D:\software\miniconda3\envs\...\Lib\site-packages\EdgeGPT.py", line 1052, in log_and_send_query
    name = str(Cookie.current_filepath.name)
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Cookie' has no attribute 'current_filepath'. Did you mean: 'current_file_index'?
python-BaseException

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

.

### Version where the problem happens

0.6.9

### What Python version are you running this with?

3.9

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by acheong08** [comment]
I am extremely confused as to why this happened. Nothing was changed in regards to current_filepath. Can someone please review this? https://github.com/acheong08/EdgeGPT/compare/0.6.8...0.6.9

**Comment by acheong08** [comment]
Can somebody review the latest commit and see if it fixes it?
To install latest commit: `pip install git+https://github.com/acheong08/EdgeGPT.git --break-system-packages`

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.6.10

**Comment by acheong08** [comment]
Read the release notes
