### ISSUE TITLE
[Bug]: 0.6.10, "No valid cookie file found."

### ISSUE THREAD

**Issue by iaston** [acheong08/EdgeGPT#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

cookie_bing.json locate in the same folder of .py, but still can not be found.  Windows + python 3.11

Code:
`ans = Query(question, proxy=g_proxy, style="balanced", cookie_file=r"./cookie_bing.json")
`
or
```
g_current_dir = os.getcwd()
ans = Query(question, proxy=g_proxy, style="balanced", cookie_file=g_current_dir + "\cookie_bing.json")

```
Error info:
Traceback (most recent call last):
  File "D:\software\miniconda3\envs\...\Lib\site-packages\EdgeGPT.py", line 975, in import_data
    raise "No valid cookie file found." from exc
TypeError: exceptions must derive from BaseException

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

.

### Version where the problem happens

.

### What Python version are you running this with?

3.11

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
.
```

### Console logs

```Shell
.
```

**Comment by acheong08** [comment]
> `For Query class, make sure to set cookie file name to bing_cookies_*.json (e.g. bing_cookies_main.json)`
