### ISSUE TITLE
New version(0.7.2) not support Python 3.8

### ISSUE THREAD

**Issue by The---onE** [acheong08/EdgeGPT#471]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Alternative  syntax for unions is new feature of Python 3.10
Union[] is better for Python 3.8+

### Steps to reproduce the problem

from EdgeGPT import Chatbot, ConversationStyle

### What should have happened?

import modules

### Version where the problem happens

0.7.2

### What Python version are you running this with?

3.8.10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\My\AI-Chat\Server\api.py", line 7, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\EdgeGPT.py", line 179, in <module>
    LOCATION_HINT_TYPES = Optional[LocationHint | Literal["USA", "CHINA", "EU",
"UK"]]
TypeError: unsupported operand type(s) for |: 'EnumMeta' and '_GenericAlias'
```

### Additional information

Line 180:LOCATION_HINT_TYPES = Optional[Union[LocationHint, Literal["USA", "CHINA", "EU", "UK"]]]
Line 254:ConversationStyle | Literal["creative", "balanced", "precise"]
Line 299:if not isinstance(cookie_file, str | Path):

**Comment by acheong08** [comment]
Python is very annoying
