### ISSUE TITLE
[Bug]: Query can not be used unauthenticated

### ISSUE THREAD

**Issue by StolenGalaxy** [acheong08/EdgeGPT#473]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Currently, when you try to use the Query class without a cookie file it gives an error, although the Chatbot class can be used withoutn cookies.

### Steps to reproduce the problem

print(Query("Hello", "creative")) without a cookie file

### What should have happened?

The response of the prompt "Hello" should have been printed.

### Version where the problem happens

0.7.2

### What Python version are you running this with?

3.11.1

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
raise "No valid cookie file found." from exc
TypeError: exceptions must derive from BaseException
```

**Comment by manatlan** [comment]
and it's not very clear, how to pass a cookie to `Query()` ...

**Comment by acheong08** [comment]
CC @PFython

**Comment by PFython** [comment]
I'll update the README shortly - new version coming soon :)

**Comment by PFython** [comment]
See https://github.com/acheong08/EdgeGPT/pull/507
