### ISSUE TITLE
[Bug]: TypeError: unsupported operand type(s) for |: 'EnumMeta' and '_GenericAlias'+解决方法

### ISSUE THREAD

**Issue by JimouChen** [acheong08/EdgeGPT#475]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

- 更新到0.7.2，出现下面👇这个问题：
```
TypeError: unsupported operand type(s) for |: 'EnumMeta' and '_GenericAlias'
```
原因：使用了|运算符来连接两种不同的类型：EnumMeta和_GenericAlias。这个运算符只能用于连接两个相同类型的枚举类，使用Union来代替|

### Steps to reproduce the problem

```python
from EdgeGPT import Query
```
- version
```
EdgeGPT==0.7.2
python==3.9
```

### What should have happened?

- 解决方法：
```python
LOCATION_HINT_TYPES = Optional[Union[LocationHint, Literal["USA", "CHINA", "EU", "UK"]]]
```
- 同理修改下面的：
```python
# CONVERSATION_STYLE_TYPE = Optional[
#     ConversationStyle | Literal["creative", "balanced", "precise"]
# ]

CONVERSATION_STYLE_TYPE = Optional[Union[
    ConversationStyle, Literal["creative", "balanced", "precise"]
]]
```
- 修改之后，没有报错，可以成功执行

### Version where the problem happens

`EdgeGPT==0.7.2`
`python==3.9`

### What Python version are you running this with?

3.9

### What is your operating system ?

MacOS

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
TypeError: unsupported operand type(s) for |: 'EnumMeta' and '_GenericAlias'
```

**Comment by VMTask** [comment]
开一个pr
