### ISSUE TITLE
Authentication failed caused by 302 redirect

### ISSUE THREAD

**Issue by superhermes** [acheong08/EdgeGPT#48]
for cookie in cookie_file:

            self.session.cookies.set(cookie["name"], cookie["value"])

        # url = "https://www.bing.com/turing/conversation/create"

        url="https://cn.bing.com/turing/conversation/create"

        # Send GET request

        response = self.session.get(
            url,
            timeout_seconds=30,
            headers=headers,
        )

Get the url https://www.bing.com/turing/conversation/create will get a 302 response which redirect to new url,The Authentication fail.
change the new url works.Maybe it’s about the region.

**Comment by acheong08** [comment]
I might be able to fix this with a allow redirect flag. Do you mind hanging around to test it?

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.0.41

**Comment by acheong08** [comment]
If this doesn't work, it means that you can't use this in China

**Comment by superhermes** [comment]
![image](https://user-images.githubusercontent.com/25399631/219010816-14cc42ad-ada7-4ff1-a738-55e3e6d13be9.png)

**Comment by superhermes** [comment]
The new version([bf93dd7](https://github.com/acheong08/EdgeGPT/commit/bf93dd7aeec2094b2d231998f2d651ac8522620d))is work
