### ISSUE TITLE
[Feature Request]: receive the picture that the Sydney send.

### ISSUE THREAD

**Issue by wuxin008** [acheong08/EdgeGPT#486]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

when we ask Sydney to send a picture to me, it is imposiible to receive that image because we can only receive plain text. So I hope this project can receive the picture that Sydney send to me. Any method of storing images is ok, such as saving them as files. I just want to see the pictures.

### Proposed workflow

sorry:(, I don't know how to make a project...

**Comment by Yorddyyorddy** [comment]
you can receive the image link  but with some garbage texts

Do just like this 
`query =  bot.ask(prompt=msg.text, conversation_style=ConversationStyle.creative)
   `
`print(query["item"]["messages"][1]["adaptiveCards"][0]["body"][0]["text"])`
