### ISSUE TITLE
[Bug]: New version(v0.8.1) not support Chinese system

### ISSUE THREAD

**Issue by The---onE** [acheong08/EdgeGPT#488]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Throw exception while asking Bing by Chinese
Exception: InvalidRequest: Culture is not supported. (Parameter 'name')
Chinese (Simplified)-People's Republic of China is an invalid culture identifier

### Steps to reproduce the problem

Run it in Chinese system, and ask Bing by Chinese

### What should have happened?

Answer the question

### Version where the problem happens

0.8.1

### What Python version are you running this with?

3.8,10

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "api.py", line 132, in bing_main
    response = await bot.ask(prompt, conversation_style=conversation_style)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\EdgeGPT.py", line 753, in ask
    async for final, response in self.chat_hub.ask_stream(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-p
ackages\EdgeGPT.py", line 658, in ask_stream
    raise Exception(
Exception: InvalidRequest: Culture is not supported. (Parameter 'name')
Chinese (Simplified)-People's Republic of China is an invalid culture identifier
.
Traceback (most recent call last):
  File "api.py", line 211, in bing_request
    quotes = message["adaptiveCards"][0]["body"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by d1h1r1** [comment]
ans = await bot.ask(prompt=txt, conversation_style=ConversationStyle.creative, locale="zh-cn")自己指定地区就可以了

**Comment by The---onE** [comment]
> 

好像是Windows平台的问题，getlocale获取的格式不是en_US这样
指定locale在连续第二次请求之后传递不过去，PR #489 可以修复这个
