### ISSUE TITLE
[Bug]: cant recongnize EdgeUtils even after downloading the pip package

### ISSUE THREAD

**Issue by TheLime1** [acheong08/EdgeGPT#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

 didnt recongnize EdgeUtils 

### Steps to reproduce the problem

```
from EdgeUtils import ImageQuery
q = ImageQuery("Meerkats at a garden party in Devon")
```

### What should have happened?

the programm run

### Version where the problem happens

Name: revChatGPT
Version: 6.0.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API
Home-page: https://github.com/acheong08/ChatGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: C:\Users\everp\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: async-tio, curl-cffi, httpx, openai, OpenAIAuth, prompt-toolkit, requests, tiktoken
Required-by:

### What Python version are you running this with?

Python 3.11.3

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
PS C:\Users\everp\Documents\GitHub\gpt-cli\test\bingimage> & C:/Users/everp/AppData/Local/Programs/Python/Python311/python.exe c:/Users/everp/Documents/GitHub/gpt-cli/test/bingimage/testimage.py
Traceback (most recent call last):
  File "c:\Users\everp\Documents\GitHub\gpt-cli\test\bingimage\testimage.py", line 1, in <module>
    from EdgeUtils import ImageQuery
ModuleNotFoundError: No module named 'EdgeUtils'
PS C:\Users\everp\Documents\GitHub\gpt-cli\test\bingimage>
```

**Comment by MonsterDruide1** [comment]
> Name: revChatGPT
Version: 6.0.2
Summary: ChatGPT is a reverse engineering of OpenAI's ChatGPT API

... seems wrong. Make sure you are on the latest version of EdgeGPT, using `python3 -m pip install EdgeGPT --upgrade`.

**Comment by Linger206** [comment]
Seems related to commit 23f6095
EdgeUtils was newly added but not included in setup.py

**Comment by d1h1r1** [comment]
可以在当前路径自己新建一个EdgeUtils.py，然后把代码复制进去就可以了
