### ISSUE TITLE
[Bug]: History and Cookie File not working

### ISSUE THREAD

**Issue by ProfDrLuigi** [acheong08/EdgeGPT#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

If I try to set the history or cookie file I get this. With older Versions i had no problem.

### Steps to reproduce the problem

.

### What should have happened?

.

### Version where the problem happens

.

### What Python version are you running this with?

3.10

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
python EdgeGPT.py --cookie-file /mnt/homeshare/edgegpt/9931
```

### Console logs

```Shell
Initializing...
Enter `alt+enter` or `escape+enter` to send a message
Traceback (most recent call last):
  File "/home/pi/test/EdgeGPT/src/EdgeGPT.py", line 391, in <module>
    main()
  File "/home/pi/test/EdgeGPT/src/EdgeGPT.py", line 387, in main
    asyncio.run(async_main(args))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/pi/test/EdgeGPT/src/EdgeGPT.py", line 222, in async_main
    cookies = json.loads(Path.open(args.cookie_file, encoding="utf-8").read())
  File "/usr/lib/python3.10/pathlib.py", line 1119, in open
    return self._accessor.open(self, mode, buffering, encoding, errors,
AttributeError: 'str' object has no attribute '_accessor'
```

**Comment by acheong08** [comment]
It failed to read the file. Cannot replicate with `--cookie-file ./cookies.json`

**Comment by ProfDrLuigi** [comment]
I tried it now this way:

`python -m EdgeGPT.EdgeGPT --cookie-file ./cookies.json`

But get the same accessor Error again. Cookie file is definetely in place.

**Comment by acheong08** [comment]
ChatGPT figured it out

**Comment by ProfDrLuigi** [comment]
The same error with 0.10.1 

If I start EdgeGPT without any options it's working.  But with any options not.
