### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'src.helpers'

### ISSUE THREAD

**Issue by Zapzatron** [acheong08/EdgeGPT#499]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 1, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 23, in <module>
    from src.helpers.chathub.chathub import ChatHub
ModuleNotFoundError: No module named 'src.helpers'

### Steps to reproduce the problem

from EdgeGPT import Chatbot, ConversationStyle

### What should have happened?

...

### Version where the problem happens

0.9.1

### What Python version are you running this with?

3.10.9

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
Traceback (most recent call last):
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\tests\bing_AI.py", line 1, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
  File "F:\Games\Programming_Projects\Python\telegram_bots\Zapzatron_Bot\venv\lib\site-packages\EdgeGPT.py", line 23, in <module>
    from src.helpers.chathub.chathub import ChatHub
ModuleNotFoundError: No module named 'src.helpers'
```

**Comment by MonsterDruide1** [comment]
Might be fixed by #497

**Comment by phamxtien** [comment]
in EdgeGPT.py, change
```
from src.helpers.chathub.chathub import ChatHub
from src..helpers.chathub.request import ChatHubRequest
from src.helpers.conversation import Conversation
from src..helpers.conversation_style import CONVERSATION_STYLE_TYPE
from src..helpers.utilities import guess_locale

```
to
```
from .helpers.chathub.chathub import ChatHub
from .helpers.chathub.request import ChatHubRequest
from .helpers.conversation import Conversation
from .helpers.conversation_style import CONVERSATION_STYLE_TYPE
from .helpers.utilities import guess_locale
```

**Comment by Well2333** [comment]
> 

agree with that

**Comment by Well2333** [comment]
> I think the best way would be to create an "EdgeGPT" directory with all the files in it.

agree with that

**Comment by acheong08** [comment]
> I think the best way would be to create an "EdgeGPT" directory with all the files in it.

Done

**Comment by Zapzatron** [comment]
Thx
