### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by zjrwtx** [acheong08/EdgeGPT#5]
![image](https://user-images.githubusercontent.com/86822589/218022344-0bc149e2-92a9-4d4f-bb9f-d1847bb43e79.png)

**Comment by acheong08** [comment]
You didn't upgrade

**Comment by acheong08** [comment]
`pip3 install --upgrade EdgeGPT`

**Comment by zjrwtx** [comment]
> `pip3 install --upgrade EdgeGPT`

already upgrade but still the same error

**Comment by acheong08** [comment]
`pip3 show EdgeGPT`

**Comment by zjrwtx** [comment]
![image](https://user-images.githubusercontent.com/86822589/218023681-33af5e50-6ba4-4f0f-b252-6c693135e38d.png)

**Comment by acheong08** [comment]
The error shows code from an outdated version

**Comment by acheong08** [comment]
Yeah, that is extremely outdated

**Comment by acheong08** [comment]
`pip3 uninstall EdgeGPT`

`pip3 install EdgeGPT`

**Comment by zjrwtx** [comment]
<img width="843" alt="1421ec6359177acc553d1b2cbe2ce57" src="https://user-images.githubusercontent.com/86822589/218024339-e8b046cd-c3a9-4629-9cb6-54aaf4c8ef3a.png">


> `pip3 uninstall EdgeGPT`
> 
> `pip3 install EdgeGPT`

Uninstall and reinstall, same version, same error

**Comment by acheong08** [comment]
You're using a PyPi proxy which caches versions

**Comment by acheong08** [comment]
`git clone https://github.com/acheong08/EdgeGPT`
`cd EdgeGPT`
`pip3 install .`

**Comment by acheong08** [comment]
The latest version is `0.0.10` https://github.com/acheong08/EdgeGPT/releases/tag/0.0.10

**Comment by zjrwtx** [comment]
it works ,but there is a new error :
![image](https://user-images.githubusercontent.com/86822589/218026895-cecd9bd2-6ec0-4b68-955b-a47c8dba6a36.png)
