### ISSUE TITLE
[Feature Request]: 添加breaking警告或撤回部分改动

### ISSUE THREAD

**Issue by Well2333** [acheong08/EdgeGPT#500]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

在 0.9.0 的项目目录重构中，部分导入例如 `ConversationStyle` 位置改变，导致部分用户在升级后代码不可用。同时，我查看了相关的pr和release，并没有发现任何警告或任何说明。

我建议开发者在release中添加breaking警告，说明哪些部分发生了变化，以及如何修改代码来适应新的版本。如果可能的话，撤回部分改动，保持原有的项目结构，以免影响已有的用户。

这是相关的pr和release链接：
https://github.com/acheong08/EdgeGPT/commit/f0b6c7c7a9bd58d6534ce487ad77a901cdb6b918
https://github.com/acheong08/EdgeGPT/releases/tag/0.9.0

### Proposed workflow

例如将部分内容重新 import 回现存的入口文件中，而且目前的这个目录会在 site-packages 中创建新的 helpers 文件夹，而这可能会造成潜在的风险，例如与别的包的文件重合，建议统一放入 EdgeGPT 自己的目录中而不是全部塞到 site-packages 下

**Comment by Well2333** [comment]
实际上 #499 就是因为这次 breaking 导致的问题

**Comment by acheong08** [comment]
> 例如将部分内容重新 import 回现存的入口文件中，而且目前的这个目录会在 site-packages 中创建新的 helpers 文件夹，而这可能会造成潜在的风险，例如与别的包的文件重合，建议统一放入 EdgeGPT 自己的目录中而不是全部塞到 site-packages 下

Addressed by https://github.com/acheong08/EdgeGPT/releases/tag/0.10.0 with some release notes

**Comment by acheong08** [comment]
I usually use an increment in 0.x to denote some API changes. This one was more major and probably should have warranted an increment in x.0

**Comment by Hansimov** [comment]
Release 0.10.0 is awesome!
