### ISSUE TITLE
[Bug]: cannot import name 'Chatbot' from 'EdgeGPT'

### ISSUE THREAD

**Issue by chimera15** [acheong08/EdgeGPT#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Two of us with new installs have run into this issue. 

cannot import name 'Chatbot' from 'EdgeGPT'

INFO:Loading the extension "EdgeGPT"...
ERROR:Failed to load the extension "EdgeGPT".
Traceback (most recent call last):
  File "L:\vicuna\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "L:\vicuna\text-generation-webui\extensions\EdgeGPT\script.py", line 7, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (C:\Users\lrdce\anaconda3\envs\textgen\Lib\site-packages\EdgeGPT__init__.py)
init.py appears to be empty

both of us have tried on two machines each, did we miss an install step or something? 

### Steps to reproduce the problem

just trying to start the plugin anytime we start oobabooga

### What should have happened?

it should load

### Version where the problem happens

new install fresh pull

### What Python version are you running this with?

3.10.6

### Command Line Arguments

```Shell
python server.py --chat --extensions EdgeGPT
```

### Console logs

```Shell
(textgen) L:\vicuna\text-generation-webui>python server.py --chat --extensions EdgeGPT
INFO:Loading the extension "EdgeGPT"...
ERROR:Failed to load the extension "EdgeGPT".
Traceback (most recent call last):
  File "L:\vicuna\text-generation-webui\modules\extensions.py", line 34, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "L:\vicuna\text-generation-webui\extensions\EdgeGPT\script.py", line 7, in <module>
    from EdgeGPT import Chatbot, ConversationStyle
ImportError: cannot import name 'Chatbot' from 'EdgeGPT' (C:\Users\lrdce\anaconda3\envs\textgen\Lib\site-packages\EdgeGPT\__init__.py)
INFO:Loading the extension "gallery"...
Running on local URL:  http://127.0.0.1:7861
```

**Comment by acheong08** [comment]
Documented in https://github.com/acheong08/EdgeGPT/releases/tag/0.10.0 release notes

**Comment by chimera15** [comment]
can you be more specific? I don't understand how that fixes the problem?

**Comment by acheong08** [comment]
Send me the extension github and I will open a PR

**Comment by chimera15** [comment]
https://github.com/GiusTex/EdgeGPT

**Comment by acheong08** [comment]
I opened PR
