### ISSUE TITLE
How to support multi-turn question answering and what parameters are required?

### ISSUE THREAD

**Issue by ouwx** [acheong08/EdgeGPT#524]
How to support multi-turn question answering and what parameters are required?

**Comment by phamxtien** [comment]
save_conversation
async def save_conversation(filename: str) -> None
Save the conversation to a file

load_conversation
async def load_conversation(filename: str) -> None
Load the conversation from a file

https://github.com/acheong08/EdgeGPT/blob/main/docs/wiki/EdgeGPT.md

**Comment by acheong08** [comment]
Just keep using the same chatbot object

**Comment by danchiche** [comment]
I tested 10 times without save_conversation and load_conversation and all the times it don't want to continue and it display a like a new conversation
before the big update (last week) it works like a charm, and ALL the times

**Comment by acheong08** [comment]
No changes were made regarding save_conversation and load_conversation.

**Comment by danchiche** [comment]
for sure
do you want the bot.ask() answer for the first answer, and the bot.ask() answer for the second ?

**Comment by ouwx** [comment]
now ,i am using the same chatbot object
