### ISSUE TITLE
Can i store cookie with environment variable instead of cookie.json?

### ISSUE THREAD

**Issue by xcloudx12345** [acheong08/EdgeGPT#54]
i try to run it on replit and store the cookie in json, It doesn't seem safe
Is there any other way to login?

**Comment by acheong08** [comment]
> It doesn't seem safe

What doesn't seem safe?

> Can i store cookie with environment variable instead of cookie.json

Make a pull request if you wish as an option

**Comment by Manamama** [comment]
IMHO, placing these in that separate JSON file is exactly as safe as placing them in the env variable. They both get referenced by the code. If "the enemy" has access to your JSON then they have equal access to your .bashrc or wherever you may keep that variable. 

Interestingly enough the cookie session works some days after. See also my today's [end-user "naive" comments](https://github.com/acheong08/EdgeGPT/discussions/69#discussioncomment-5074296) about Edge Chat session impermanence and how they wipe it with human toxic answers, to avoid Taybot chat session cache problems.

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.0.52
