### ISSUE TITLE
[Bug]: No module named EdgeGPT.__main__

### ISSUE THREAD

**Issue by Allen-c-HE** [acheong08/EdgeGPT#549]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Error reported when running since version 0.9.2:
No module named EdgeGPT.__main__; 'EdgeGPT' is a package and cannot be directly executed

### Steps to reproduce the problem

-

### What should have happened?

-

### Version where the problem happens

0.9.0 and later

### What Python version are you running this with?

3.11

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
-
```

### Console logs

```Shell
-
```

**Comment by acheong08** [comment]
`python -m EdgeGPT.EdgeGPT`
