### ISSUE TITLE
[Bug]: Problem while generating images

### ISSUE THREAD

**Issue by dralucindaodonto** [acheong08/EdgeGPT#550]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I encounter an issue when attempting to generate images using EdgeGPT. During the image generation process, I receive a large HTML response from Bing, which results in an error. Has anyone else experienced this problem? If so, could you please provide some guidance on successfully generating images with EdgeGPT? Any help would be greatly appreciated.

### Steps to reproduce the problem

run the image generation example from the docs

### What should have happened?

generate images from bing.

### Version where the problem happens

Receiving an HTML and a error

### Command Line Arguments

```Shell
no
```

### Console logs

```Shell
Traceback (most recent call last):
  File "C:\Edge2-GPT\image_generation.py", line 16, in <module>
    images = image_generator.get_images(args.prompt)
  File "C:\Users\Admin\.pyenv\pyenv-win\versions\3.9.10\lib\site-packages\BingImageCreator.py", line 138, in get_images
    raise Exception(error_redirect)
Exception: Redirect failed
Traceback (most recent call last):
  File "C:\Edge2-GPT\img.py", line 40, in <module>
    asyncio.run(main())
  File "C:\Users\Admin\.pyenv\pyenv-win\versions\3.9.10\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\.pyenv\pyenv-win\versions\3.9.10\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Edge2-GPT\img.py", line 35, in main
    await chat_with_bot(bot, cookies)
  File "C:\Edge2-GPT\img.py", line 16, in chat_with_bot
    subprocess.run(["python", "image_generation.py", "--prompt", prompt, "--U", U_cookie], check=True)
  File "C:\Users\Admin\.pyenv\pyenv-win\versions\3.9.10\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python', 'image_generation.py', '--prompt', 'a dog', '--U', '1fLa31IVBt1RNj7Xb1lceREUUfFnkFcbiZBWa1lf5fWYxxZdc-FdtfeJegctH_s2JoJCUgJk6PteBBBv0e2-CiCa-K-bO4Mf94WJnyhCrrpn5XlxrR_z10UV7UXFDtEi7zWBztfAHnhif4DtT_QLhLW57kYcGYJcu35KNJz1DgeSskTuLEpR_bRf-FHs-13YyH5HSW3GMq1hedENzjmdWUg']' returned non-zero exit status 1.
```

### Additional information

I need to generate the images

**Comment by AdityaSher** [comment]
Receiving the same error

**Comment by deepdatalive** [comment]
+1 same issue

**Comment by manatlan** [comment]
The trouble is in **BingImageCreator** (a lib used by edgegpt, from the same author)
On my side : I've got better result (no redirect error), using the env var setted : 

`BING_URL=https://cn.bing.com
`
despite, i'm in france ...

perhaps it could work better for you ...

**Comment by acheong08** [comment]
It's my fault. In the process of copy pasting / refactoring, some stuff got cut out.

**Comment by manatlan** [comment]
@acheong08  ... the latest release 0.11.1 ... is the perfect version !
everything works ! thanks a lot !

ok, I need to override the BING_URL (to generate image with bing image creator)
And need to override the BING_PROXY_URL (to call myself **https://edgeservices.bing.com/edgesvc/turing/conversation/create** from another server ... to obtain news conversations id)
and the creative mode "draw me a red cat" works like in the pas !

thanks a lot !

**Comment by acheong08** [comment]
@manatlan To use the `cn` extension?

**Comment by manatlan** [comment]
Yes, I need to use the cn version, from my French server (on my French provider)
I think MS think it's IP is Chinese ...

But all works as expected
