### ISSUE TITLE
[Bug]: aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

### ISSUE THREAD

**Issue by VMTask** [acheong08/EdgeGPT#553]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I run thsi program,It show me this error:
aiohttp.client_exceptions.WSServerHandshakeError: 403, message='Invalid response status', url=URL('wss://sydney.bing.com/sydney/ChatHub')

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

Stable

### Version where the problem happens

Name: EdgeGPT
Version: 0.10.16
Summary: Reverse engineered Edge Chat API
Home-page: https://github.com/acheong08/EdgeGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: C:\Users\VMTask\AppData\Local\Programs\Python\Python311\Lib\site-packages
Requires: aiohttp, BingImageCreator, certifi, httpx, prompt-toolkit, requests, rich, websockets
Required-by:

### What Python version are you running this with?

Python 3.11.0

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
I don't want to provide.
```

**Comment by VMTask** [comment]
I don't want to use 0.8.2 now.

**Comment by manatlan** [comment]
The "bing" implem of "G4F" (gpt4free) doesn't have this trouble :
https://gitler.moe/manatlan/gpt4free/src/branch/main/g4f/Provider/Providers/helpers/bing.py

The code is a lot simpler, and help me to understand the "whole image" (how http/wss exchanges works with bing ia)

But I haven't found the trouble in edgegpt ... and I mainly use G4F for now.

**Comment by acheong08** [comment]
I haven't been able to reproduce this error. Any hints?

**Comment by acheong08** [comment]
I added some headers. Test latest commit

**Comment by acheong08** [comment]
@VMTask https://github.com/acheong08/EdgeGPT/releases/tag/0.11.0

**Comment by acheong08** [comment]
Check websockets branch to see if aiohttp is the issue https://github.com/acheong08/EdgeGPT/tree/websockets

**Comment by acheong08** [comment]
> The code is a lot simpler

Yeah I do feel like this repo has become a somewhat confusing mess

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.11.0

**Comment by manatlan** [comment]
@acheong08 : for me it's ok (no more wss handshake errors)
I switch from 0.8.2 to the newest 0.11.0 !

But a prompt like "draw me a blue car" doesn't work in "creative" mode ... (redirect error, line 111 in bingimagecreator.py)
It worked in the past ...

**Comment by manatlan** [comment]
@acheong08 
In fact, edgegpt is very dependant of "bing api changes".
So this depot should concentrate to implement the protocol, at the lower level, and only the protocol.
And adopt KISS (keep simple and stupid).
With simple unittests/pytests (which could be the doc of use of the api), to cover 99to100% the code base.
To make it "rock solid" (and when "bugs" : it will be on bing api changes only ...)

things like store/restore conversations, and query/utils should be in another depot based on edgegpt.

(never reach to use "Query" (the idea is good) ... but doesn't seem to work)

**Comment by acheong08** [comment]
Not quite sure  about the future of this project. I can't really keep up with all the changes by Bing considering I only have a few hours a day available (between 11PM and 2AM)
