### ISSUE TITLE
Some times after 2 or 3 conversations it gives KeyError: 'adaptiveCards'

### ISSUE THREAD

**Issue by Meshwa428** [acheong08/EdgeGPT#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I was using the bing chat by prompting it my own custom built Jarvis prompt which I use often some times

and this happens only some times, like after 2 or 3 conversations it shows this sort of error like key error of adaptive cards or sugestions 

I am in windows, using python 3.11.3 and latest version of EdgeGPT

Using it with SpeechRecognition library

Here is a little debug details:
                    |
                   \/

You : hey jarvis how are the service doing right now.

Jarvis : All systems are running smoothly, sir. I'm monitoring your devices, accessories, and systems for any issues or updates. Is there anything you need me to check or optimize for you?👨‍💻

Listening...
Recognizing...

You : what about the server.

Jarvis : The server is functioning well, sir. It has a 99.9% uptime and a low latency. The security is also up to date and no threats have been detected. Do you want me to perform a backup or a scan on the server?🔒

Listening...
Recognizing...

You : yeah sure do they scan for the time causes a little bit lower than before it was 100% right.
Traceback (most recent call last):
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 69, in <module>
    ClapDetect()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 65, in ClapDetect
    MainExecution()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 55, in MainExecution
    Reply = asyncio.run(edgegpt(str(Data)))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 10, in edgegpt
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 136, in ask
    "sources_text": message["adaptiveCards"][0]["body"][-1]["text"],
                    ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'adaptiveCards'

### Steps to reproduce the problem

None

### What should have happened?

I dont know

### Version where the problem happens

I think the problem might have happened from here

            if final:
                if not simplify_response:
                    return response
                message = response["item"]["messages"][-1]
                for s in reversed(response['item']['messages']):
                    if 'messageType' not in s:
                        message = s
                        break
                return {
                    "text": message["text"],
                    "author": message["author"],
                    "sources": message.get("sourceAttributions"),
                    "sources_text": message["adaptiveCards"][0]["body"][-1]["text"],  <------------- This part of code
                    "suggestions": [
                        suggestion["text"]
                        for suggestion in message["suggestedResponses"]
                    ],
                    "messages_left": response["item"]["throttling"][
                        "maxNumUserMessagesInConversation"
                    ]
                    - response["item"]["throttling"]["numUserMessagesInConversation"],
                    "adaptive_text": message["adaptiveCards"][0]["body"][0]["text"],
                }
        return {}

### What Python version are you running this with?

3.11.3

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
None
```


### Console logs

```Shell
Traceback (most recent call last):
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 69, in <module>
    ClapDetect()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 65, in ClapDetect
    MainExecution()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 55, in MainExecution
    Reply = asyncio.run(edgegpt(str(Data)))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 10, in edgegpt
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 136, in ask
    "sources_text": message["adaptiveCards"][0]["body"][-1]["text"],
                    ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'adaptiveCards'
```


### Additional information

None

**Comment by DeadBranches** [comment]
Hi, I have a possible solution for you to try.

The KeyError is caused by trying to access a key that does not exist in the dictionary. To avoid this error, you can use the .get() method instead of the square brackets [] to get the value for a key. The .get() method allows you to specify a default value to return if the key is not found, instead of raising an exception.

Specifically, instead of this line:

`sources_text = message[“adaptiveCards”][0][“body”][-1][“text”]`

You can use this line:

`sources_text = message.get(“adaptiveCards”, [“”])[0][“body”][-1].get(“text”, “”)`

This way, if the key `adaptiveCards` is not found in message, or if the list is empty, it will return a list with an empty string [“”], and then you can access the first element [0] without an error. If the key `text` is not found in the last dictionary, it will return an empty string “”.

**Comment by Meshwa428** [comment]
But bro this part of code ( sources_text = message[“adaptiveCards”][0][“body”][-1][“text”] ) is inside the module, its the part of EdgeGPT.py, even if i change it, after an update it will be gone and I would have to do it again, so I suggest @acheong08 to fix it, so if any other person is getting the same error then it will be fixed if they update to the newer versions

**Comment by acheong08** [comment]
I'll fix it
