### ISSUE TITLE
How can we get the streamed response, as we were able to get with the revChatGPT

### ISSUE THREAD

**Issue by Meshwa428** [acheong08/EdgeGPT#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

This is one of the example that were mentioned in the revChatGPT repo

from revChatGPT.V1 import Chatbot
chatbot = Chatbot(config={
  "access_token": "<your access_token>"
})
print("Chatbot: ")
prev_text = ""
for data in chatbot.ask(
    "Hello world",
):
    message = data["message"][len(prev_text) :]
    print(message, end="", flush=True)
    prev_text = data["message"]
print()

### Proposed workflow

None

### Additional information

None

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/blob/4b2f533f24f52362a3bc7328c4cb6052d5b14016/src/EdgeGPT/main.py#L160-L174
