### ISSUE TITLE
[Bug]: Same error happens even after fix #559 KeyError: 'adaptiveCards'

### ISSUE THREAD

**Issue by Meshwa428** [acheong08/EdgeGPT#566]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

Jarvis : Hello sir, JARVIS is ready to assist you. It is morning 11:35 AM in India. How may I help you today? 😊

Listening...
Recognizing...

You : find me some information about the new ai released by meta.
Traceback (most recent call last):
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 86, in <module>
    ClapDetect()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 82, in ClapDetect
    MainExecution()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 72, in MainExecution

  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 14, in edgegpt
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 139, in ask
    "sources_text": message["adaptiveCards"][0]["body"][-1]["text"],
                    ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'adaptiveCards'

### Steps to reproduce the problem

None

### What should have happened?

            if final:
                if not simplify_response:
                    return response
                message = next(
                    (
                        s
                        for s in reversed(response["item"]["messages"])
                        if "messageType" not in s
                    ),
                    response["item"]["messages"][-1],
                )
                return {
                    "text": message["text"],
                    "author": message["author"],
                    "sources": message.get("sourceAttributions"),
                    "sources_text": message["adaptiveCards"][0]["body"][-1]["text"],  <--------------  Same part, Same error again 
                    "suggestions": [
                        suggestion["text"]
                        for suggestion in message["suggestedResponses"]
                    ],
                    "messages_left": response["item"]["throttling"][
                        "maxNumUserMessagesInConversation"
                    ]
                    - response["item"]["throttling"]["numUserMessagesInConversation"],
                    "adaptive_text": message["adaptiveCards"][0]["body"][0].get("text"),
                }
        return {}

### Version where the problem happens

Name: EdgeGPT
Version: 0.11.2
Summary: Reverse engineered Edge Chat API
Home-page: https://github.com/acheong08/EdgeGPT
Author: Antonio Cheong

### What Python version are you running this with?

3.11.3

### What is your operating system ?

_No response_

### Command Line Arguments

```Shell
None
```


### Console logs

```Shell
Traceback (most recent call last):
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 86, in <module>
    ClapDetect()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 82, in ClapDetect
    MainExecution()
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Jarvis.py", line 72, in MainExecution

  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "P:\J.A.R.V.I.S\Jarvis Using Python\Brain\Qna.py", line 14, in edgegpt
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative, simplify_response=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\vandu\AppData\Local\Programs\Python\Python311\Lib\site-packages\EdgeGPT\EdgeGPT.py", line 139, in ask
    "sources_text": message["adaptiveCards"][0]["body"][-1]["text"],
                    ~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'adaptiveCards'
```


### Additional information

None

**Comment by Meshwa428** [comment]
I think that the problem might me in the response which is extracted from bing, adaptive cards field sometimes appears and sometimes not thats why it gives the error again and again

**Comment by acheong08** [comment]
Failed to replicate with same prompt. Can you provide minimum code to replicate the issue?

**Comment by Meshwa428** [comment]
This only happens when i try to use simplify_response
When i tried it without simplify_response it just works as intended


import asyncio, json
from EdgeGPT.EdgeGPT import Chatbot, ConversationStyle

cookies = json.loads(open("Data/cookies.json", encoding="utf-8").read())

# Main function to get the response from EdgeGPT
async def edgegpt(prompt):
    bot = await Chatbot.create(cookies=cookies)

    # Loading the conversation
    await bot.load_conversation(filename="Data/bing_history.json")

    # Getting the response from Bing
    response = await bot.ask(prompt=prompt, conversation_style=ConversationStyle.creative)#, simplify_response=True)
    response = json.dumps(response, indent=2)

    # Saving the conversation
    await bot.save_conversation(filename="Data/bing_history.json")
    final_text = response["item"]["messages"][1]["text"]
    await bot.close()
    return final_text

**Comment by acheong08** [comment]
> final_text = response["item"]["messages"][1]["text"]

This is not how you use simplify response

**Comment by acheong08** [comment]
This is what simplify response returns:
```py
{
                    "text": message["text"],
                    "author": message["author"],
                    "sources": message.get("sourceAttributions"),
                    "sources_text": message["adaptiveCards"][0]["body"][-1]["text"],
                    "suggestions": [
                        suggestion["text"]
                        for suggestion in message["suggestedResponses"]
                    ],
                    "messages_left": response["item"]["throttling"][
                        "maxNumUserMessagesInConversation"
                    ]
                    - response["item"]["throttling"]["numUserMessagesInConversation"],
                    "adaptive_text": message["adaptiveCards"][0]["body"][0].get("text"),
                    "total_messages": response["item"]["throttling"][
                        "maxNumUserMessagesInConversation"
                    ],
                }
```

**Comment by acheong08** [comment]
You can get the adaptive text from the simplified response via:
```
final_text = response["adaptive_text"]

**Comment by bassie661** [comment]
You can fix it in the file chathub.py, with adding a check to see if 'adaptiveCards' key exists before accessing it:

in the second part -> and not draw:
              ```
                              # Check if 'adaptiveCards' key exists before accessing it
                                            if (
                                                "messages" in response["arguments"][0]
                                                and response["arguments"][0]["messages"]
                                                and "adaptiveCards" in response["arguments"][0]["messages"][0]
                                            ):
```
