### ISSUE TITLE
[Bug]: Requirement already satisfied:

### ISSUE THREAD

**Issue by yuandj** [acheong08/EdgeGPT#572]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Requirement already satisfied: httpx[socks]>=0.24.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (0.24.1)
Requirement already satisfied: aiohttp in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (3.8.4)
Requirement already satisfied: websockets in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (11.0.3)
Requirement already satisfied: rich in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (13.4.2)
Requirement already satisfied: certifi in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (2023.5.7)
Requirement already satisfied: prompt-toolkit in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (3.0.38)
Requirement already satisfied: requests in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (2.31.0)
Requirement already satisfied: BingImageCreator>=0.3.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (0.4.2)
Requirement already satisfied: regex in c:\users\administrator\desktop\2022\py31\lib\site-packages (from BingImageCreator>=0.3.0->EdgeGPT) (2023.6.3)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT) (0.17.2)
Requirement already satisfied: idna in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT) (3.4)
Requirement already satisfied: sniffio in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT) (1.3.0)
Requirement already satisfied: socksio==1.* in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT) (1.0.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (1.3.1)
Requirement already satisfied: wcwidth in c:\users\administrator\desktop\2022\py31\lib\site-packages (from prompt-toolkit->EdgeGPT) (0.2.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from requests->EdgeGPT) (2.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from rich->EdgeGPT) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from rich->EdgeGPT) (2.15.1)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx[socks]>=0.24.0->EdgeGPT) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx[socks]>=0.24.0->EdgeGPT) (3.7.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from markdown-it-py>=2.2.0->rich->EdgeGPT) (0.1.2)
Installing collected packages: EdgeGPT
  Attempting uninstall: EdgeGPT
    Found existing installation: EdgeGPT 0.11.1
    Uninstalling EdgeGPT-0.11.1:
      Successfully uninstalled EdgeGPT-0.11.1
Successfully installed EdgeGPT-0.11.6

### Steps to reproduce the problem

1. Go to ....
2. Press ....
3. ...

### What should have happened?

I'm not sure I already updated.

### Version where the problem happens

I using the python3 to overwrite old python 

### Command Line Arguments

```Shell
python -m pip install EdgeGPT --upgrade
```

### Console logs

```Shell
Requirement already satisfied: httpx[socks]>=0.24.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (0.24.1)
Requirement already satisfied: aiohttp in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (3.8.4)
Requirement already satisfied: websockets in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (11.0.3)
Requirement already satisfied: rich in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (13.4.2)
Requirement already satisfied: certifi in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (2023.5.7)
Requirement already satisfied: prompt-toolkit in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (3.0.38)
Requirement already satisfied: requests in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (2.31.0)
Requirement already satisfied: BingImageCreator>=0.3.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from EdgeGPT) (0.4.2)
Requirement already satisfied: regex in c:\users\administrator\desktop\2022\py31\lib\site-packages (from BingImageCreator>=0.3.0->EdgeGPT) (2023.6.3)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT) (0.17.2)
Requirement already satisfied: idna in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT) (3.4)
Requirement already satisfied: sniffio in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT) (1.3.0)
Requirement already satisfied: socksio==1.* in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpx[socks]>=0.24.0->EdgeGPT) (1.0.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from aiohttp->EdgeGPT) (1.3.1)
Requirement already satisfied: wcwidth in c:\users\administrator\desktop\2022\py31\lib\site-packages (from prompt-toolkit->EdgeGPT) (0.2.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from requests->EdgeGPT) (2.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from rich->EdgeGPT) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from rich->EdgeGPT) (2.15.1)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx[socks]>=0.24.0->EdgeGPT) (0.14.0)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from httpcore<0.18.0,>=0.15.0->httpx[socks]>=0.24.0->EdgeGPT) (3.7.0)
Requirement already satisfied: mdurl~=0.1 in c:\users\administrator\desktop\2022\py31\lib\site-packages (from markdown-it-py>=2.2.0->rich->EdgeGPT) (0.1.2)
Installing collected packages: EdgeGPT
  Attempting uninstall: EdgeGPT
    Found existing installation: EdgeGPT 0.11.1
    Uninstalling EdgeGPT-0.11.1:
      Successfully uninstalled EdgeGPT-0.11.1
Successfully installed EdgeGPT-0.11.6
```

**Comment by acheong08** [comment]
It means installation is successful lol
