### ISSUE TITLE
Exception: Authentication failed. You have not been accepted into the beta.

### ISSUE THREAD

**Issue by Smiorld** [acheong08/EdgeGPT#59]
I've looked through several closed issues, my issue is not included.
I'm sure I have the access to new bing.
![image](https://user-images.githubusercontent.com/39952090/219516136-3de02a75-dd40-4a22-8cbd-bf1a7815967f.png)

This exception occurs from time to time. And as I looked through my cookie, I can not find _U anywhere (neither on chrome nor edge).

Chrome: www.bing.com
![image](https://user-images.githubusercontent.com/39952090/219516481-b214b58b-508c-487f-840c-1da1219dd169.png)

Edge: www.bing.com
![image](https://user-images.githubusercontent.com/39952090/219516542-6a2e9ca0-7627-4dc6-871e-8bded98443e3.png)

Is this causing the issue?

**Comment by Smiorld** [comment]
According to my observation, it is likely because of I'm using a work account.
When I logged in with my personal account( which doesn't have access to the new bing), the _U cookie appears even after I switch my account back to the work account, and the _U cookie remains the same as my personal account's.
But if I logged out of my personal account, the _U cookie disappears along with it.
Not 100% sure about it though.

**Comment by acheong08** [comment]
If your work and personal account is linked, that could cause issues with the cookie. There could be other forms of authentication we do not know of for work accounts

**Comment by acheong08** [comment]
You can try to reverse engineer by copying the request from the developer menu as a cURL command and pasting it in terminal. If it works, keep removing details until it doesn't so that we can identify the exact authentication measure

**Comment by Smiorld** [comment]
Thank you for your advice.
I'm indeed interested in reverse engineering but I'm new to this concept. 
Are there any documents/tutorials I could refer to?
P.S. it fails as I tried to ask questions in the chat future now, but it worked several hours ago.
![HDRP1WU%CM3EU`%%VYQ)8_I](https://user-images.githubusercontent.com/39952090/219523111-fffc52cc-5538-47c7-90c6-67fd827c88b2.png)
Does that mean my account get banned?

**Comment by acheong08** [comment]
> Does that mean my account get banned?

Yes. It is currently unknown what causes the bans. I have already implemented exact cookies and headers as well as tls spoofing.

**Comment by Smiorld** [comment]
I guess I've sent several bad requests which trigger the ban. But unfortunately, I didn't save the output log during my test :(

**Comment by TingoLee** [comment]
It seems like bing chat is currently down. If you search on twitter, there are many users report this issue.

**Comment by Blankeer** [comment]
> 谢谢你的建议。我确实对逆向工程感兴趣，但我对这个概念很陌生。是否有任何我可以参考的文档/教程？附言它失败了，因为我现在试图在聊天未来中提问，但它在几个小时前起作用了。 ![HDRP1WU%CM3EU'%%VYQ）8_I](https://user-images.githubusercontent.com/39952090/219523111-fffc52cc-5538-47c7-90c6-67fd827c88b2.png)这是否意味着我的帐户被禁止？

The exception I'm getting is `Sorry, you are not allowed to access this service.`
<img width="1098" alt="image" src="https://user-images.githubusercontent.com/8948303/219524901-30383c22-6e7f-4c26-ac37-864dd4c81b9d.png">
Is the account blocked?

**Comment by Smiorld** [comment]
![image](https://user-images.githubusercontent.com/39952090/219527564-69326c6e-0f8d-4ca9-9dda-ea73de3a0d6a.png)
This is what I found on Reddit

**Comment by vaibhavk97** [comment]
I started having this issue shortly, have they started banning accounts?

**Comment by acheong08** [comment]
https://twitter.com/POZ04yFIPYYirjs/status/1625796351740235778
https://twitter.com/search?q=Bing%20Something%20went%20wrong.&src=typed_query
https://twitter.com/tommeehancfi/status/1625244653590028289

**Comment by acheong08** [comment]
It seems it's a general outage. Nobody is able to access right now even if they don't use this library

**Comment by Harry-Jing** [comment]
I thought I have been baned form bing before I saw this issue

**Comment by acheong08** [comment]
> I thought I have been baned form bing before I saw this issue

same

**Comment by QiuZiXian** [comment]
> 

same

**Comment by fkcptlst** [comment]
所以说现在还没好么？（我这边还没好）

**Comment by Harry-Jing** [comment]
我这边也没有，昨天做的bot，今天就炸了

**Comment by acheong08** [comment]
It'll work in a few hours or maybe days

**Comment by acheong08** [comment]
Waiting on Microsoft to fix it

**Comment by skrleo** [comment]
Waiting on Microsoft to fix

**Comment by arielherself** [comment]
> ![image](https://user-images.githubusercontent.com/39952090/219527564-69326c6e-0f8d-4ca9-9dda-ea73de3a0d6a.png)
> 
> This is what I found on Reddit [thread link](https://www.reddit.com/r/bing/comments/1146zd6/bing_ai_constantly_attempting_to_reconnect/)

The description in that thread is not consistent with what we experienced. According to my survey, the chat service has been available for most users in recent hours, thus I think it's almost clear that our accounts are shadow-banned by Microsoft.

**Comment by acheong08** [comment]
This is possible. If your account still doesn't work, it is likely shadow-banned. Both of my accounts are working now

**Comment by fkcptlst** [comment]
Any evidence of what exactly is causing the ban? Proxy issues? Or because of the hacking?

**Comment by arielherself** [comment]
![image](https://user-images.githubusercontent.com/107245128/219657313-a7f00003-61f3-41ae-9e54-70c9709f64e8.png)
As you see, after clearing all data of Edge, I still have the same trouble. If your accounts are working now, maybe my situation is not typical. I can't tell if it's this lib to blame. By the way, I think proxy may not be a decisive factor, because I have been using the new Bing through proxy since 2/12, and it wasn't until earlier today that my account was “banned”.

**Comment by Harry-Jing** [comment]
![image](https://user-images.githubusercontent.com/69247286/219661888-2d05f4a1-c0f5-4c7a-94dc-0bbb9677b07e.png)
I also can't access to new bing. T_T

**Comment by fkcptlst** [comment]
no worries. I can't either

**Comment by Harry-Jing** [comment]
I'm really worried if I get permanently banned

**Comment by acheong08** [comment]
I don't think it's a ban. We set up a poll and 47 / 50 people not even using EdgeGPT or other reverse engineered solutions are experiencing the same problem

**Comment by akitell** [comment]
It was working normally, then I had the same problem. Now I'm getting this error: 'Authentication failed. You have not been accepted into the beta. :(

**Comment by akitell** [comment]
> ![image](https://user-images.githubusercontent.com/107245128/219657313-a7f00003-61f3-41ae-9e54-70c9709f64e8.png) As you see, after clearing all data of Edge, I still have the same trouble. If your accounts are working now, maybe my situation is not typical. I can't tell if it's this lib to blame. By the way, I think proxy may not be a decisive factor, because I have been using the new Bing through proxy since 2/12, and it wasn't until earlier today that my account was “banned”.

same error...

**Comment by parthmalhotra** [comment]
I think bing is detecting on the basis of subsequent tracking / chat completion / suggestion requests being not made to their servers using the python script, On the basis of that they might be flagging users. A puppeteer type solution which spawns edge and then simulates the typing of the prompt with human typing speed, To gather the data burp suite/transparent proxy can be used to create an event hook to send the prompt response back can be used as an hacky solution until bing releases an official api.

**Comment by getxd-dev** [comment]
All you can do is wait, it works again for me after 12 hours.

**Comment by Smiorld** [comment]
> All you can do is wait, it works again for me after 12 hours.

Yes, it works. I guess it's time to close the issue.

**Comment by acheong08** [comment]
Keeping it open until Microsoft allows access again. We're not the only ones affected. Pretty much everyone who had access to the new Bing, regardless if they use reverse engineered repos.

**Comment by acheong08** [comment]
If it works for you again, please comment

**Comment by acheong08** [comment]
oh shit it works for me now

**Comment by acheong08** [comment]
@Harry-Jing @fkcptlst comment

**Comment by fkcptlst** [comment]
just checked. working now

**Comment by Harry-Jing** [comment]
my account also work

**Comment by acheong08** [comment]
closing then

**Comment by acheong08** [comment]
btw got official approval from Sydney/Bing/Microsoft developer that our reverse engineering is fine

**Comment by acheong08** [comment]
We're not breaking TOS

**Comment by Harry-Jing** [comment]
This is really good news.
