### ISSUE TITLE
[Bug]:  cannot import name 'ImageQuery' from 'EdgeGPT'

### ISSUE THREAD

**Issue by sharepointmike** [acheong08/EdgeGPT#592]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Just following the example:

from EdgeGPT import ImageQuery
q=ImageQuery("Meerkats at a garden party in Devon")

### Steps to reproduce the problem

Just copied the lines of code above

### What should have happened?

Import should have worked?

### Version where the problem happens

latest

### What Python version are you running this with?

latest

### What is your operating system ?

Windows

### Command Line Arguments

```Shell
none
```

### Console logs

```Shell
nothing
```

**Comment by acheong08** [comment]
`from EdgeGPT.EdgeUtils import ImageQuery`

docs were updated

**Comment by sharepointmike** [comment]
Thanks,
If I use that I get "IndexError: list index out of range" on the next line: q=ImageQuery("Meerkats at a garden party in Devon")

**Comment by acheong08** [comment]
EdgeUtils is unmaintained. Use https://github.com/acheong08/BingImageCreator/ instead

**Comment by sharepointmike** [comment]
Hi Antonio,

Is there some sample python code how to use it?

Thanks, MIke
