### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by RLBOT1v1Replayproprogrammer** [acheong08/EdgeGPT#6]
![image](https://user-images.githubusercontent.com/67492572/218029533-1a070a64-9dc8-4144-a4a6-0b80d09406e1.png)

**Comment by Jimmy-Z** [comment]
I think this is a duplication of #4, check https://github.com/acheong08/EdgeGPT/issues/4#issuecomment-1425313279

**Comment by acheong08** [comment]
Duplicate
