### ISSUE TITLE
[Bug]: websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200 when I use the script on a server

### ISSUE THREAD

**Issue by IKDH** [acheong08/EdgeGPT#621]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I use the script on a server, I have this error : websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200

When I use the same script with the same IP (I use a proxy) on my computer, I have no problem.

In both case, I don't use cookies.

### Steps to reproduce the problem

1. Go to ....a
2. Press ....
3. ...

### What should have happened?

The script should work on a server.

### Version where the problem happens

All

### What Python version are you running this with?

3.9

### What is your operating system ?

Linux

### Command Line Arguments

```Shell
No
```

### Console logs

```Shell
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 200
```

**Comment by asmigiulati** [comment]
I am facing the same problem when i run it on replit

**Comment by IKDH** [comment]
Does anyone has successfully run the program in cloud server like AWS ?

**Comment by xuxin3101** [comment]
Perhaps a proxy is needed for the WSS connection (using Warp in a cloud server), but WebSockets don't support proxies. I switched to aiohttp, but encountered a new error: aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer. However, I'm confident that Warp can be used with Bing, as the project https://github.com/waylaidwanderer/node-chatgpt-api runs smoothly on the same cloud server.

**Comment by F33RNI** [comment]
Same. Versions after 0.10.16 do not work with proxies =(

**Comment by OlegRuban-ai** [comment]
The same problem, it starts locally, but doesn't work on a remote server

**Comment by xuxin3101** [comment]
fixed
https://github.com/acheong08/EdgeGPT/pull/627

**Comment by asmigulati** [comment]
Hi, I am still encountering the same error!
