### ISSUE TITLE
Click “New topic” to chat about something else.

### ISSUE THREAD

**Issue by Smiorld** [acheong08/EdgeGPT#63]
![image](https://user-images.githubusercontent.com/39952090/219827860-21edb349-b2ca-48fc-9a48-60b8caa970d2.png)

There seems to be a limitation on the total number of messages within a conversation, which forces users to click "New Topic" manually.

![image](https://user-images.githubusercontent.com/39952090/219827814-26bc6a9b-22ec-4414-be2b-8166b36c75fb.png)

Any chance to fix this? 
tbh it would be very weird to auto click "New Topic" after receiving the limitation signal because the conversation will no longer be consistent.

**Comment by acheong08** [comment]
"New topic" == "reset()" in this code base
