### ISSUE TITLE
"Something went wrong. Please try again." when join the waitlist

### ISSUE THREAD

**Issue by zhayujie** [acheong08/EdgeGPT#65]
Hello, do you know how to join the waitlist of new bing?

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/26161723/219874281-1ee6bbfe-406a-47ef-af78-4cf2bd1fa365.png">

**Comment by Manamama** [comment]
Whatever and however you do, join it asap. They are limiting it by the day, see my other posts here.

**Comment by acheong08** [comment]
not my problem. complain to MS
