### ISSUE TITLE
Request is throttled

### ISSUE THREAD

**Issue by LUORANCHENG** [acheong08/EdgeGPT#72]
When I use the api multiple times, the request is throttled

code:
````
import asyncio
from EdgeGPT import Chatbot

async def main():
    bot = Chatbot(cookiePath='cookie.txt')
    print((await bot.ask(prompt="hello,who are you?")))
    await bot.close()


if __name__ == "__main__":
    asyncio.run(main())
````

error:
`
{'type': 2, 'invocationId': '0', 'item': {'firstNewMessageIndex': None, 'conversationId': '51D|BingProd|7AA9DBBD86992941648A09E8BEFF084C9D8C3B6DA01F5E929CC2ABD7B4E3B0D1', 'requestId': 'f2fe4018-cfec-430d-ae43-7f753881dde9', 'telemetry': {'metrics': None, 'startTime': '2023-02-22T03:11:44.2953465Z'}, 'result': {'value': 'Throttled', 'message': 'Request is throttled.', 'error': 'Request is throttled.', 'serviceVersion': '20230221.134'}}}
`

**Comment by acheong08** [comment]
Issue from Microsoft. They are rate limiting
