### ISSUE TITLE
[:rocket:	Feature] Add Rich API for a more colorfull response (maybe also parse Markdown etc.)

### ISSUE THREAD

**Issue by semmjon** [acheong08/EdgeGPT#76]
Would be nice when we could create a more colorful CLI. Maybe ich can try to implement this if i have the time :-)

https://github.com/Textualize/rich

**Comment by acheong08** [comment]
Not my expertise. Will need help

**Comment by PRO-2684** [comment]
Response Markdown parsing: #126
