### ISSUE TITLE
[REQUEST] Sharing my cookies.json file.

### ISSUE THREAD

**Issue by LuckyHead11** [acheong08/EdgeGPT#79]
Just a simple request if you'd like. I would like to share my cookies.json file so that others can enjoy Bing GPT. Personally, I see no use because ChatGPT extensions that give it web access exist, so I don't care if it gets disabled.

So I'm just wondering if you would like the cookies.json file. For example, you can store it in the code internally so that if you don't include the --cookie-file param then it defaults to it.

**Comment by acheong08** [comment]
There is a severe rate limit.

As for sharing without exposing your account to hackers, I did make https://github.com/acheong08/SydneyAuth a while back which allows the sharing of conversationIDs

**Comment by acheong08** [comment]
I think most people got access now though.

**Comment by LuckyHead11** [comment]
ok @acheong08
