### ISSUE TITLE
get the cookies.json using python

### ISSUE THREAD

**Issue by lucasXing24** [acheong08/EdgeGPT#81]
Is there someway to use python to get the cookies.json?

**Comment by marhmm** [comment]
I would appreciate a solution to get the cookies.json directly by python.
Right now, I use a selenium script to login to microsoft and get the needed cookie (it is the cookie with "name": "KievRPSSecAuth")
This seems to work, but I think it is a bit too complicated.

**Comment by acheong08** [comment]
Won't support directly. Can use third party
