### ISSUE TITLE
SSL Certification Verification Error

### ISSUE THREAD

**Issue by andr3wV** [acheong08/EdgeGPT#82]
Keep getting this error every time. Anyone know what's wrong? I have access to the new Bing so I don't think it's a cookies problem, but I'm not sure. 

`
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)
`

**Comment by andr3wV** [comment]
Just realized this is a duplicate my b

**Comment by QiongHacker** [comment]
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
