### ISSUE TITLE
Is EdgeGPT setting my IP when calling GPT?

### ISSUE THREAD

**Issue by ldp12416** [acheong08/EdgeGPT#83]
Is EdgeGPT setting my IP? The results I get from EdgeGPT are different from the results I get from GPT using bing. For example, when I ask about today’s news, the result of EdgeGPT should be from a certain country, but not from where my IP is located.

**Comment by acheong08** [comment]
Some privacy invasive trackers were removed, including location tracking. You have to tell it where to pull information from.

**Comment by acheong08** [comment]
I also added some IP spoofing for the Chinese users so that it gets unblocked

**Comment by ldp12416** [comment]
> You have to tell it where to pull information from

How to do this?

**Comment by ldp12416** [comment]
> I also added some IP spoofing for the Chinese users so that it gets unblocked

My IP is not from China.

**Comment by acheong08** [comment]
> My IP is not from China.

I mean it is default. It randomizes an IP originating from Microsoft

> How to do this?

"What is today's news for <country>"

**Comment by ldp12416** [comment]
> "What is today's news for "

Thanks, I will try it.

**Comment by ldp12416** [comment]
> I mean it is default. It randomizes an IP originating from Microsoft

What should I do if I want to change the random IP to my real IP?

**Comment by acheong08** [comment]
Remove forwarded IP

https://github.com/acheong08/EdgeGPT/blob/0166313ca08490913b694b5edc72808d522c80d1/src/EdgeGPT.py#L21-L46

**Comment by ldp12416** [comment]
Got it. I will try it. Thanks a lot!

**Comment by ldp12416** [comment]
> "x-forwarded-for": FORWARDED_IP,

I've commented the above line and reinstall the package. But the results are still not right as I ask bing GPT directly. For example:
1. When I ask EdgeGPT today's news, the results come from 2021, or even before.
2. Another thing is that  EdgeGPT can work even with a Chinese IP. So I guess the IP spoofing is not removed correctly.

> Some privacy invasive trackers were removed, including location tracking.

Would you please tell how to recover the locaion tracking? I'd like to try that and see if it will work.

**Comment by ldp12416** [comment]
> 2\. Another thing is that  EdgeGPT can work even with a Chinese IP. So I guess the IP spoofing is not removed correctly.

I guess this is because the cookie I use is from an IP out of China. Never mind.
