### ISSUE TITLE
[feature request] Support conversation style 

### ISSUE THREAD

**Issue by BeautyyuYanli** [acheong08/EdgeGPT#89]
Recently New Bing added the conversation style selection:

![Screenshot_20230302-044331_Pixel Launcher.png](https://user-images.githubusercontent.com/32453863/222260646-918b81e0-74e3-42de-b09a-ecee9d449b1c.png)

**Comment by Harry-Jing** [comment]
Same request

**Comment by Harry-Jing** [comment]
A way to implement it #91
