### ISSUE TITLE
conversation.struct={'result': {'value': 'UnauthorizedRequest', 'message': 'Sorry, you need to login first to access this service.'}}

### ISSUE THREAD

**Issue by xjd-ziyu** [acheong08/EdgeGPT#9]
I ran normally on my personal computer, when i change a computer, it reported a bug. After checking it, I found that 

conversation. struct={'result ': {'value': 'UnauthorizedRequest', 'message': 'Sorry, you need to login first to access this service.'}} 

it led to 

self. request=ChatHubRequest（
conversation_ signature=conversation.struct["conversationSignature"],
client_ id=conversation.struct["clientId"],
conversation_ id=conversation.struct["conversationId"],
)

Error.
Excuse me, is the version I downloaded too low or does it need other configurations?

**Comment by xjd-ziyu** [comment]
> pip3 show EdgeGPT

Name: EdgeGPT
Version: 0.0.10
Summary: Reverse engineered Edge Chat API
Home-page: https://github.com/acheong08/EdgeGPT
Author: Antonio Cheong
Author-email: acheong@student.dalat.org
License: GNU General Public License v2.0
Location: /home/work/local/python3.8.6/lib/python3.8/site-packages
Requires: asyncio, requests, websockets
Required-by:

**Comment by acheong08** [comment]
Current version is https://github.com/acheong08/EdgeGPT/releases/tag/0.0.20

**Comment by xjd-ziyu** [comment]
> Current version is https://github.com/acheong08/EdgeGPT/releases/tag/0.0.20

Thank you. I'll try again with a new version.

**Comment by xjd-ziyu** [comment]
> pip3 show EdgeGPT

sorry，it dosen't work. It still have the same problem when I switch the version to Version: 0.0.20.

**Comment by xjd-ziyu** [comment]
It may not be a version problem, because I think another computer that can run successfully is installed with 0.0.10

**Comment by acheong08** [comment]
Did you try to define your own cookie?

**Comment by acheong08** [comment]
How are you running it?

**Comment by xjd-ziyu** [comment]
> Did you try to define your own cookie?

I'm using the default running method. I'm sorry that the wrong computer can't install a browser. So I can't get the cookie. Is it possible that this is the cause of the error?

**Comment by acheong08** [comment]
It should work out of the box. Not sure where the error comes from. Try again a few times

**Comment by xjd-ziyu** [comment]
> It should work out of the box. Not sure where the error comes from. Try again a few times and add some debugging statements
sorry, excuse me, there is a new bug.
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/65710139/218098274-1fe7664d-ca4a-45de-bed6-682487f1c4e1.png">
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='bing.kpham.workers.dev', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fda71bc8370>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by acheong08** [comment]
https://github.com/acheong08/EdgeGPT/releases/tag/0.0.25
