### ISSUE TITLE
Daily chat limit

### ISSUE THREAD

**Issue by XiaoXinYo** [acheong08/EdgeGPT#94]
Is there any way to break the upper limit?

**Comment by acheong08** [comment]
yes but I haven't written it properly yet. haven't had the time

**Comment by leolrg** [comment]
Yes, pm me for how to do it

**Comment by nagaisa** [comment]
> Yes, I know how bypass the limit but I can't implement it because I have no experience in web-related stuffs.

how do you do it?

**Comment by acheong08** [comment]
https://github.com/waylaidwanderer/node-chatgpt-api/releases/tag/v1.25.0

He got there first

**Comment by xcloudx12345** [comment]
> [waylaidwanderer/node-chatgpt-api#132](https://github.com/waylaidwanderer/node-chatgpt-api/pull/132) He got there first

It looks like MS discovered and patched it.

**Comment by waylaidwanderer** [comment]
@xcloudx12345 Nah I tested it just now and it's still working fine.

**Comment by menachem1** [comment]
Is anyone working on this?

**Comment by acheong08** [comment]
No plans on adding jailbreak. Keeping this vanilla.
