### ISSUE TITLE
Request is throttled, do we need proxy?

### ISSUE THREAD

**Issue by hafidzaini** [acheong08/EdgeGPT#95]
`{'type': 2, 'invocationId': '0', 'item': {'firstNewMessageIndex': None, 'conversationId': '51D|BingProd|F2093AB67E3F9AA7EDC37F59A02121AE3EDDE94B9C754D1C953A6B0E47A36193', 'requestId': 'a29326cf-38fb-4dc3-ad24-a85cf730d341', 'telemetry': {'metrics': None, 'startTime': '2023-03-03T13:37:21.0941181Z'}, 'result': {'value': 'Throttled', 'message': 'Request is throttled.', 'error': 'Request is throttled.', 'serviceVersion': '20230228.87'}}}`

it was error from my VPS but not on my desktop.
is it because of IP? how to set proxy?

**Comment by acheong08** [comment]
You just got to wait for a day. It's a limit of 100 conversations per day

**Comment by hafidzaini** [comment]
> > 今天再次在我的VPS上工作。看起来他们也为帐户和IP设置了限制🤔
> 
> 我也遇到了这个问题，请问你解决了吗？

try using proxy.
when i use the script on different box, it was still running fine
